/** Pure, bounded model input. A stored file reference is never parsed binary content. */
export interface AssetInputSource {id:string;name:string;mimeType:string;bytes:number;sha256:string;version:number;createdAt:number;text?:string;image?:unknown;referenceOnly?:boolean;contentKind?:'file';hasImage?:boolean}
export interface AssetInputMeeting {meetingFolder?:{path:string;files:{id:string;fileId:string;kind:string;version:number;sha256:string;relativePath:string}[]}}
export const isReferenceAsset=(asset:AssetInputSource)=>asset.referenceOnly===true||(asset.text===undefined&&!asset.image&&!asset.hasImage)
export const assetImageRef=(asset:AssetInputSource)=>isReferenceAsset(asset)?undefined:asset.image
export function assetReferenceMetadata(asset:AssetInputSource,meeting?:AssetInputMeeting){const ref=meeting?.meetingFolder?.files.find(ref=>ref.kind==='asset'&&ref.id===asset.id&&ref.version===asset.version&&ref.sha256===asset.sha256);return {id:asset.id,name:asset.name,bytes:asset.bytes,mimeType:asset.mimeType,version:asset.version,sha256:asset.sha256,...(ref?{fileId:ref.fileId,relativePath:ref.relativePath,approvedPath:meeting!.meetingFolder!.path.replace(/[\\/]+$/,'')+'/'+ref.relativePath}:{}),referenceOnly:isReferenceAsset(asset),parsed:!isReferenceAsset(asset)&&asset.text!==undefined}}
export function assetInputText(asset:AssetInputSource,meeting?:AssetInputMeeting,imageIncluded=true):string {const ref=assetReferenceMetadata(asset,meeting),header=`附件 ${asset.name} · v${asset.version} · ${asset.bytes}字节 · MIME ${asset.mimeType} · SHA256 ${asset.sha256}${ref.approvedPath?`\n已批准原件位置：${ref.approvedPath}\n文件标识：${ref.fileId}`:''}`;if(ref.referenceOnly)return `${header}\n这是完整文件原件引用，内容未解析；仅名称、大小、类型、版本与校验信息可知。原件不自动解压或读取，不把二进制/base64注入模型；不能凭文件名、路径或扩展名猜测内容，也不能称已理解。`;return `${header}\n${asset.text!==undefined?asset.text:(asset.image||asset.hasImage)?imageIncluded?'图片作为真实image内容随本条投递；接收模型需支持图片。未提供文字解析，不能只凭文件名推断图片事实。':'这是图像引用元信息，当前秘书输入未提供像素或解析内容；不能从图片名称、路径或类型推断事实。':'内容未解析'}`}
export const AssetInputText=assetInputText
/** Secretary/workflow copies omit image handles and opaque text/binary caches. */
export function assetModelSnapshot(asset:AssetInputSource,meeting?:AssetInputMeeting){const metadata=assetReferenceMetadata(asset,meeting);return {id:asset.id,name:asset.name,mimeType:asset.mimeType,bytes:asset.bytes,sha256:asset.sha256,version:asset.version,createdAt:asset.createdAt,...(asset.contentKind?{contentKind:asset.contentKind}:{}),...(metadata.referenceOnly?{referenceOnly:true}:asset.text!==undefined?{text:asset.text}:{}),...(!metadata.referenceOnly&&(asset.image||asset.hasImage)?{hasImage:true}:{}),...(metadata.fileId?{fileId:metadata.fileId,relativePath:metadata.relativePath,approvedPath:metadata.approvedPath}:{}),inputText:assetInputText(asset,meeting,false),parsed:!metadata.referenceOnly&&asset.text!==undefined}}
/** Strip any accidental opaque caches before secretary JSON or model budgeting. */
export function sanitizeAssetReferences(value:unknown):unknown {
 if(Array.isArray(value))return value.map(sanitizeAssetReferences)
 if(!value||typeof value!=='object')return value
 const record=value as Record<string,unknown>,reference=record.referenceOnly===true||(typeof record.name==='string'&&typeof record.mimeType==='string'&&(typeof record.bytes==='number'||typeof record.size==='number')&&record.text===undefined&&!record.image&&!record.hasImage)
 if(reference){const keys=['id','fileId','kind','name','mimeType','bytes','size','version','sha256','createdAt','time','relativePath','approvedPath'],result:Record<string,unknown>={referenceOnly:true,parsed:false,contentStatus:'仅完整原件引用，内容未解析；无二进制/base64注入，不自动解压，也不凭名称推断事实。'};for(const key of keys){const field=record[key];if(typeof field==='string'||typeof field==='number')result[key]=field}return result}
 return Object.fromEntries(Object.entries(record).map(([key,item])=>[key,sanitizeAssetReferences(item)]))
}
