import {assetInputText,assetImageRef,isReferenceAsset} from './asset-reference.ts'
import {createHash} from 'node:crypto'
import type {Context} from '@deepseek-ai/cordis'
import {SessionId,type Session} from '@deepseek-ai/dsh-session'
import {createUserMessage,freezeMessage} from '@deepseek-ai/dsh-llm/message'
import {mutateMeeting,stateRoot,listMeetings,requireActiveMeeting,type Meeting} from './meetings.ts'
import {withMeetingActivity} from './meeting-activity.ts'
import {readStoredSession,sessionHistory} from './host-runtime.ts'
import {memberForExecution,memberIsArchived} from './member-session.ts'
import type {DiscussionRecord,DiscussionDelivery} from './discussion-types.ts'
function discussionResponseInstruction(m:Meeting,d:DiscussionRecord):string {const g=m.taskCardGenerations?.find(g=>g.discussionId===d.id);return g?`本次是明确的任务卡${g.kind==='adjust'?'调整':'生成'}准备请求。必须使用 meeting_propose_task_cards(meetingId,generationId,discussionId,items,emptyReason,requestId)，generationId=${g.id}。${g.kind==='adjust'?'只返回所指卡片这一项，不重生成其他卡。':'一事项一卡；没有待办返回空items及真实emptyReason。'}只提交一次本成员清单，同次重试保持原requestId及内容；不要仅调用meeting_reply_message代替任务卡清单。准备卡片不授权执行、认领、完成或验收。`: '用 meeting_reply_message(meetingId,discussionId,text,requestId) 向会议回传本次讨论回复；每次新的阶段反馈使用新requestId，同次重试保持原requestId与正文。'}
const messageText=(m:Meeting,d:DiscussionRecord,sid:string)=>`[圆桌会议「${m.title}」·普通讨论消息]\nmeetingId=${m.meetingId}\ndiscussionId=${d.id}\n接收者=${sid}\n${d.contextTaskId?`关联既有任务（仅澄清，不变更任务范围）：${d.contextTaskId}\n`:''}主持人正文：${d.instruction}\n\n只使用以下明确选择的资料，不补读私聊：\n${d.inputs.map(x=>`【${x.id} · ${x.sender}】\n${x.text}`).join('\n\n')||'（无引用资料）'}\n\n这是普通讨论，不是正式工作任务。只回应本次被授权的正文和资料；不要认领、完成、修改或验收既有任务，不扩大其范围。${discussionResponseInstruction(m,d)}不要提交无关私聊。回复不会自动唤醒其他成员。`
export function newDiscussion(m:Meeting,input:{instruction:string;recipientIds:string[];messageIds:string[];contextTaskId?:string},plan:{inputs:DiscussionRecord['inputs'];assetIds:string[]},requestId:string,requestHash:string):DiscussionRecord{
 const now=Date.now(),d:DiscussionRecord={id:`discussion-${requestId}`,messageId:`message-chat-${requestId}`,requestId,requestHash,instruction:input.instruction,recipientIds:[...input.recipientIds],messageIds:[...input.messageIds],assetIds:[...plan.assetIds],inputs:structuredClone(plan.inputs.map(input=>{const asset=m.assets?.find(a=>a.id===input.id);return asset&&isReferenceAsset(asset)?{...input,text:assetInputText(asset,m)}:input})),createdAt:now,...(input.contextTaskId?{contextTaskId:input.contextTaskId}:{}),deliveries:[],replies:[]}
 d.deliveries=d.recipientIds.map(toSessionId=>({toSessionId,status:'queued',hostMessageId:String(createUserMessage({content:[{type:'text',text:messageText(m,d,toSessionId)}],source:{kind:'round-table',plugin:'dsh-round-table'}}).id),updatedAt:now}));return d
}
function find(m:Meeting,id:string,sid?:string){const discussion=m.discussions?.find(x=>x.id===id),delivery=discussion?.deliveries.find(x=>x.toSessionId===sid);return {discussion,delivery}}
async function update(root:string,id:string,did:string,sid:string,fn:(d:DiscussionDelivery,m:Meeting)=>void){await mutateMeeting(root,id,m=>{const {delivery}=find(m,did,sid);if(delivery)fn(delivery,m);return m})}
function receipt(events:readonly {type:string;data:unknown}[],delivery:DiscussionDelivery):boolean{
 const matches=(message:unknown)=>{const x=message as {id?:string;source?:{kind?:string;plugin?:string};content?:{type?:string;text?:string}[]};return !!x&&x.id===delivery.hostMessageId&&x.source?.kind==='round-table'&&x.source.plugin==='dsh-round-table'&&x.content?.some(b=>b.type==='text'&&b.text===delivery.deliveryText)}
 return !!delivery.deliveryText&&events.some(e=>e.type==='user/message'?matches((e.data as {message?:unknown})?.message??e.data):e.type==='agent/inbox/spliced'&&(e.data as {inserted?:unknown[]})?.inserted?.some(matches))
}
async function evidence(ctx:Context,d:DiscussionDelivery){const stored=await readStoredSession(ctx,d.toSessionId);if(d.sessionCreatedAt===undefined||stored.meta.createdAt!==d.sessionCreatedAt||stored.meta.cwd!==d.sessionCwd)throw Error('原会话身份已变化，不能确认旧讨论消息');return receipt(stored.events,d)}
const pumps=new WeakMap<object,Promise<void>>()
async function pump(ctx:Context){const root=stateRoot(),jobs=(await listMeetings(root)).flatMap(snapshot=>(snapshot.discussions??[]).flatMap(record=>record.deliveries.map(item=>({snapshot,record,item})))).sort((a,b)=>a.record.createdAt-b.record.createdAt)
 for(const {snapshot,record,item} of jobs){if(item.status!=='queued')continue
  try{await withMeetingActivity(root,snapshot.meetingId,async()=>{
   let m=await requireActiveMeeting(root,snapshot.meetingId),{discussion,delivery}=find(m,record.id,item.toSessionId);if(!discussion||!delivery||delivery.status!=='queued')return
   if(m.archivedAt||m.deletion||!m.memberSessionIds.includes(item.toSessionId)){await update(root,m.meetingId,record.id,item.toSessionId,d=>{d.status='cancelled';d.error='会议归档、删除或成员已离会；未投递';d.updatedAt=Date.now()});return}
   if(m.releasePaused)return
   let agent:Awaited<ReturnType<typeof memberForExecution>>,stored:Awaited<ReturnType<typeof readStoredSession>>
   try{agent=await memberForExecution(ctx,item.toSessionId);stored=await readStoredSession(ctx,item.toSessionId);if(String(agent.session.id)!==item.toSessionId||stored.meta.createdAt!==agent.session.header.createdAt||stored.meta.cwd!==agent.session.header.cwd)throw Error('原会话身份校验失败');const last=stored.events.at(-1),live=last?sessionHistory(agent.session).find(e=>e.seq===last.seq):undefined;if(last&&(!live||live.type!==last.type||live.time!==last.time))throw Error('当前成员会话状态过期');if(typeof agent.followup!=='function')throw Error('宿主缺少可靠的普通消息FIFO接口')}
   catch(error){await update(root,m.meetingId,record.id,item.toSessionId,d=>{d.status='offline';d.error=`未投递：${String(error instanceof Error?error.message:error)}`;d.updatedAt=Date.now()});return}
   const images=discussion.assetIds.map(id=>{const asset=m.assets?.find(a=>a.id===id);return asset?assetImageRef(asset):undefined}).filter(Boolean)
   if(images.length){try{const api=ctx.get('sessionController');if(!api)throw Error('图片投递接口不可用');const p=await api.projections({sessionId:SessionId(item.toSessionId)},new AbortController().signal),model=p?.values.modelSelection?.next??p?.values.modelSelection?.lastUsed;const llm=ctx.get('llm') as {resolveModelInfo(p:string,m:string):Promise<{inputModalities?:string[]}>}|undefined;if(!model||!(await llm?.resolveModelInfo(model.provider,model.model))?.inputModalities?.includes('image'))throw Error('成员模型未声明支持图片');const attachments=ctx.get('attachments') as {readImage(ref:unknown):Promise<unknown>}|undefined;if(!attachments)throw Error('图片读取服务不可用');await Promise.all(images.map(ref=>attachments.readImage(ref)))}catch(error){await update(root,m.meetingId,record.id,item.toSessionId,d=>{d.status='failed';d.error=`未投递：${String(error instanceof Error?error.message:error)}`;d.updatedAt=Date.now()});return}}
   const text=messageText(m,discussion,item.toSessionId),message=freezeMessage({...createUserMessage({content:[{type:'text',text},...images.map(attachment=>({type:'image' as const,attachment:attachment as never}))],source:{kind:'round-table',plugin:'dsh-round-table'}}),id:delivery.hostMessageId as never})
   let admitted=false;await update(root,m.meetingId,record.id,item.toSessionId,(d,current)=>{if(d.status==='queued'&&!current.archivedAt&&!current.deletion&&!current.releasePaused&&current.memberSessionIds.includes(d.toSessionId)){d.status='delivering';d.deliveryText=text;d.sessionCreatedAt=stored.meta.createdAt;d.sessionCwd=stored.meta.cwd;d.updatedAt=Date.now();admitted=true}});if(!admitted)return
   try{let sent=false;await mutateMeeting(root,m.meetingId,current=>{const d=find(current,record.id,item.toSessionId).delivery;if(!d||d.status!=='delivering')return current;if(current.archivedAt||current.deletion||!current.memberSessionIds.includes(item.toSessionId)||memberIsArchived(ctx,item.toSessionId)){d.status='cancelled';d.error='成员离会或原会话/会议已归档，未投递';return current}if(current.releasePaused||ctx.agents.get(SessionId(item.toSessionId))!==agent){d.status='queued';return current}agent.followup(message);sent=true;return current});if(!sent)return
    const sessions=ctx.get('sessions') as {flush(s:Session):Promise<boolean>}|undefined;if(!sessions||!await sessions.flush(agent.session)||!await evidence(ctx,{...delivery,deliveryText:text,sessionCreatedAt:stored.meta.createdAt,sessionCwd:stored.meta.cwd}))throw Error('宿主尚未证实讨论消息持久化')
    await update(root,m.meetingId,record.id,item.toSessionId,d=>{if(d.status==='delivering'){d.status='delivered';d.deliveredAt=Date.now();d.updatedAt=Date.now();delete d.error}})
   }catch(error){await update(root,m.meetingId,record.id,item.toSessionId,d=>{if(d.status==='delivering'){d.status='uncertain';d.error=`投递待核实：${String(error instanceof Error?error.message:error)}`;d.updatedAt=Date.now()}})}
  })}catch(error){ctx.logger.warn(`讨论消息处理未完成：${String(error instanceof Error?error.message:error)}`)}
 }
}
export function pumpDiscussions(ctx:Context):Promise<void>{const old=pumps.get(ctx);if(old)return old;const p=pump(ctx).finally(()=>{if(pumps.get(ctx)===p)pumps.delete(ctx)});pumps.set(ctx,p);return p}
export async function recoverDiscussions(ctx:Context){const root=stateRoot();for(const m of await listMeetings(root))if(!m.deletion)for(const r of m.discussions??[])for(const d of r.deliveries)if(d.status==='delivering'||d.status==='uncertain'){let known=false;try{known=await evidence(ctx,d)}catch{}await update(root,m.meetingId,r.id,d.toSessionId,x=>{if(x.status==='delivering'||x.status==='uncertain'){x.status=known?'delivered':'uncertain';x.updatedAt=Date.now();if(known){x.deliveredAt??=Date.now();delete x.error}else x.error='服务重启或投递结果未知，请核对原窗口；不会自动重投'}})}}
export async function retryDiscussionDelivery(ctx:Context,meetingId:string,discussionId:string,sessionId:string){const root=stateRoot();await withMeetingActivity(root,meetingId,async()=>{const m=await requireActiveMeeting(root,meetingId),{delivery}=find(m,discussionId,sessionId);if(!delivery)throw Error('讨论投递不存在');if(m.archivedAt||m.releasePaused||!m.memberSessionIds.includes(sessionId)||memberIsArchived(ctx,sessionId))throw Error('请先恢复会议和原成员');const known=['delivering','uncertain'].includes(delivery.status);if(known&&!await evidence(ctx,delivery))throw Error('原讨论消息送达待核实，不允许盲目重投');await update(root,meetingId,discussionId,sessionId,(d,current)=>{if(current.archivedAt||current.deletion||current.releasePaused||!current.memberSessionIds.includes(sessionId)||memberIsArchived(ctx,sessionId))throw Error('成员或会议状态已变化');if(known){if(['delivering','uncertain'].includes(d.status)&&d.hostMessageId===delivery.hostMessageId){d.status='delivered';d.deliveredAt??=Date.now();delete d.error}}else if(['offline','failed'].includes(d.status)){d.status='queued';d.updatedAt=Date.now();delete d.error}})})}
export async function closeDiscussionDelivery(meetingId:string,discussionId:string,sessionId:string,confirmed:boolean){if(confirmed!==true)throw Error('请确认结束本次讨论等待；原窗口继续工作');await mutateMeeting(stateRoot(),meetingId,m=>{const d=find(m,discussionId,sessionId).delivery;if(!d)throw Error('讨论投递不存在');d.status='cancelled';d.updatedAt=Date.now();d.error='主持人结束本次讨论等待，不停止原窗口';return m})}
export async function replyDiscussion(ctx:Context,meetingId:string,discussionId:string,actor:{session:{id:unknown}},text:string,requestId?:string){
 const sid=String(actor.session.id);if(ctx.agents.get(SessionId(sid))!==actor||memberIsArchived(ctx,sid))throw Error('调用者不是当前真实且未归档成员Agent');if(typeof text!=='string'||!text.trim()||text.length>100000)throw Error('讨论回复不能为空且不超过10万字符')
 const m=await requireActiveMeeting(stateRoot(),meetingId),{discussion,delivery}=find(m,discussionId,sid);if(!discussion||!delivery||!m.memberSessionIds.includes(sid)||sid===m.secretary?.sessionId||m.archivedAt||m.deletion)throw Error('只有原讨论接收成员可回传当前会议');if(!['delivering','delivered','uncertain'].includes(delivery.status)||!await evidence(ctx,delivery))throw Error('未证实本次讨论消息已投递，不能回传')
 if(requestId!==undefined&&!/^[a-zA-Z0-9_-]{1,100}$/.test(requestId))throw Error('讨论回复请求ID非法');const key=requestId??`legacy-${createHash('sha256').update(text).digest('hex')}`,id=`message-discussion-${createHash('sha256').update(`${discussionId}\0${sid}\0${key}`).digest('hex').slice(0,32)}`
 await mutateMeeting(stateRoot(),meetingId,current=>{const {discussion:d,delivery:v}=find(current,discussionId,sid);if(!d||!v||!['delivering','delivered','uncertain'].includes(v.status)||current.archivedAt||current.deletion||!current.memberSessionIds.includes(sid)||ctx.agents.get(SessionId(sid))!==actor||memberIsArchived(ctx,sid))throw Error('成员或会议状态已变化，拒绝回传');const old=d.replies.find(r=>r.messageId===id);if(old){if(old.text!==text)throw Error('请求ID已用于另一段讨论回复');return current}const now=Date.now();v.status='delivered';v.deliveredAt??=now;d.replies.push({sessionId:sid,text,messageId:id,time:now,requestId:key});current.events.push({id,kind:'message',time:now,by:sid,text,discussionId,contextTaskId:d.contextTaskId,replyTo:[d.messageId],source:{kind:'agent',sessionId:sid}});return current});return {discussionId,messageId:id}
}
export function attachDiscussionLifecycle(ctx:Context){ctx.effect(()=>{let stopped=false;const tick=()=>{if(!stopped)void pumpDiscussions(ctx).catch(e=>ctx.logger.warn(String(e)))};const timer=setInterval(tick,2000);tick();return async()=>{stopped=true;clearInterval(timer);await pumps.get(ctx)}},'round-table: authorized discussion messages')}
