import type {MeetingMessage} from './meeting-flow-types.ts'
export type DiscussionDeliveryStatus='queued'|'offline'|'delivering'|'delivered'|'uncertain'|'failed'|'cancelled'
export interface DiscussionDelivery {toSessionId:string;status:DiscussionDeliveryStatus;hostMessageId:string;updatedAt:number;deliveredAt?:number;error?:string;sessionCreatedAt?:number;sessionCwd?:string;deliveryText?:string}
export interface DiscussionReply {sessionId:string;text:string;messageId:string;time:number;requestId?:string}
export interface DiscussionRecord {id:string;messageId:string;requestId:string;requestHash:string;instruction:string;recipientIds:string[];messageIds:string[];assetIds:string[];inputs:MeetingMessage[];createdAt:number;contextTaskId?:string;deliveries:DiscussionDelivery[];replies:DiscussionReply[]}
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string')&&new Set(v).size===v.length
export function isDiscussionRecord(value:unknown):value is DiscussionRecord{
 if(!value||typeof value!=='object')return false;const v=value as DiscussionRecord
 return [v.id,v.messageId,v.requestId,v.requestHash].every(x=>typeof x==='string'&&!!x)&&typeof v.instruction==='string'&&(!!v.instruction.trim()||Array.isArray(v.assetIds)&&v.assetIds.length>0||Array.isArray(v.messageIds)&&v.messageIds.length>0)&&Number.isFinite(v.createdAt)&&strings(v.recipientIds)&&v.recipientIds.length>0&&strings(v.messageIds)&&strings(v.assetIds)&&(v.contextTaskId===undefined||typeof v.contextTaskId==='string')&&Array.isArray(v.inputs)&&v.inputs.every(x=>x&&typeof x.id==='string'&&typeof x.text==='string')&&Array.isArray(v.deliveries)&&v.deliveries.length===v.recipientIds.length&&new Set(v.deliveries.map(d=>d.toSessionId)).size===v.deliveries.length&&v.deliveries.every(d=>d&&v.recipientIds.includes(d.toSessionId)&&['queued','offline','delivering','delivered','uncertain','failed','cancelled'].includes(d.status)&&typeof d.hostMessageId==='string'&&!!d.hostMessageId&&Number.isFinite(d.updatedAt)&&(d.sessionCreatedAt===undefined||Number.isFinite(d.sessionCreatedAt))&&(d.sessionCwd===undefined||typeof d.sessionCwd==='string')&&(d.deliveryText===undefined||typeof d.deliveryText==='string')&&(d.error===undefined||typeof d.error==='string'))&&Array.isArray(v.replies)&&v.replies.every(r=>r&&v.recipientIds.includes(r.sessionId)&&typeof r.text==='string'&&!!r.text&&typeof r.messageId==='string'&&Number.isFinite(r.time)&&(r.requestId===undefined||typeof r.requestId==='string'))
}
