import type {Context} from '@deepseek-ai/cordis'
import {createHash,randomUUID} from 'node:crypto'
import {open,lstat,rename,unlink,readdir} from 'node:fs/promises'
import {join} from 'node:path'
import {stateRoot,requireActiveMeeting,readMeeting,mutateMeeting,withMeetingLock,type Meeting} from './meetings.ts'
import {withMeetingActivity} from './meeting-activity.ts'
import type {MeetingAsset} from './meeting-flow-types.ts'
import {syncMeetingAssetFile,readApprovedMeetingAsset} from './meeting-files-sync.ts'
import {openMeetingDocumentDownload} from './meeting-folder.ts'
import {ensureOwnedDirectory,guardOwnedFilePath,openOwnedFile,hashOwnedFile,hashFileHandle,copyOwnedFile} from './meeting-file-io.ts'
export const MAX_FILE_BYTES=256*1024*1024
export const FILE_CHUNK_BYTES=512*1024
export class FileUploadRejected extends Error {readonly requestState='rejected';readonly retryable=false;readonly code:string;constructor(code:string,message?:string){super(message??code);this.code=message===undefined?'UPLOAD_REJECTED':code}}
interface UploadRecord {schemaVersion:1;meetingId:string;uploadId:string;requestId:string;fingerprint:string;name:string;mimeType:string;totalBytes:number;offset:number;status:'uploading'|'finishing'|'finished'|'cancelled';chunks:{offset:number;size:number;sha256:string}[];asset?:MeetingAsset}
const sha=(data:string|Uint8Array)=>createHash('sha256').update(data).digest('hex')
const reject=(code:string,message:string):never=>{throw new FileUploadRejected(code,message)}
const uploadID=(id:string)=>{if(!/^upload-[a-f0-9]{40}$/.test(id))reject('INVALID_UPLOAD_ID','上传标识非法；不接受任意文件路径');return id}
const directory=(mid:string,id:string)=>join(stateRoot(),mid,'uploads',uploadID(id))
const recordPath=(mid:string,id:string)=>join(directory(mid,id),'upload.json')
const payloadPath=(mid:string,id:string)=>join(directory(mid,id),'payload.bin')
const dto=(r:UploadRecord)=>({uploadId:r.uploadId,offset:r.offset,totalBytes:r.totalBytes,status:r.status,...(r.asset?{assetId:r.asset.id}:{})})
type AssetVersionInput=Pick<MeetingAsset,'id'|'name'|'mimeType'|'bytes'|'sha256'|'contentKind'|'referenceOnly'>
type AssetVersionReservation=AssetVersionInput&Pick<MeetingAsset,'version'|'createdAt'>
/** One durable allocator for both ordinary text/image and opaque file references. */
export async function reserveMeetingAssetVersion(mid:string,input:AssetVersionInput):Promise<AssetVersionReservation>{return withMeetingLock(`asset-version:${stateRoot()}:${mid}`,async()=>{
 const m=await active(mid);if(!/^asset-[a-f0-9]{64}$/.test(input.id)||!input.name||!Number.isSafeInteger(input.bytes)||input.bytes<1||!/^[a-f0-9]{64}$/.test(input.sha256))reject('INVALID_ASSET_RESERVATION','材料版本请求无效')
 const dir=join(stateRoot(),mid,'uploads');await ensureOwnedDirectory(stateRoot(),dir);const path=join(dir,'versions.json');let reservations:AssetVersionReservation[]=[]
 try{await guardOwnedFilePath(stateRoot(),path);const fd=await openOwnedFile(stateRoot(),path);try{if((await fd.stat()).size>8*1024*1024)reject('VERSION_RESERVATION_CORRUPT','材料版本记录超出范围');const record=JSON.parse(await fd.readFile('utf8')) as {schemaVersion:number;meetingId:string;assets:AssetVersionReservation[]};if(record.schemaVersion!==1||record.meetingId!==mid||!Array.isArray(record.assets)||record.assets.some(a=>!a||!/^asset-[a-f0-9]{64}$/.test(a.id)||typeof a.name!=='string'||!Number.isSafeInteger(a.version)||a.version<1||!Number.isFinite(a.createdAt)))reject('VERSION_RESERVATION_CORRUPT','材料版本记录损坏');reservations=record.assets}finally{await fd.close()}}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}
 const old=m.assets?.find(a=>a.id===input.id)??reservations.find(a=>a.id===input.id);if(old){if(old.sha256!==input.sha256||old.bytes!==input.bytes)reject('ASSET_RESERVATION_CONFLICT','同材料编号已有不同原件');return{id:old.id,name:old.name,mimeType:old.mimeType,bytes:old.bytes,sha256:old.sha256,version:old.version,createdAt:old.createdAt,...(old.contentKind?{contentKind:old.contentKind}:{}),...(old.referenceOnly!==undefined?{referenceOnly:old.referenceOnly}:{})}}
 const reserved:AssetVersionReservation={...input,version:1+Math.max(0,...[...(m.assets??[]),...reservations].filter(a=>a.name===input.name).map(a=>a.version)),createdAt:Date.now()};reservations.push(reserved)
 const tmp=path+'.'+randomUUID()+'.tmp',fd=await open(tmp,'wx',0o600);try{await fd.writeFile(JSON.stringify({schemaVersion:1,meetingId:mid,assets:reservations})+'\n');await fd.sync();await fd.close();await guardOwnedFilePath(stateRoot(),dir);await rename(tmp,path)}finally{await fd.close().catch(()=>{});await unlink(tmp).catch(()=>{})}return reserved
})}
async function readRecord(mid:string,id:string):Promise<UploadRecord>{
 const path=recordPath(mid,id);await guardOwnedFilePath(stateRoot(),path);const fd=await openOwnedFile(stateRoot(),path);let value:unknown;try{if((await fd.stat()).size>1048576)reject('UPLOAD_CORRUPT','上传记录超出范围');value=JSON.parse(await fd.readFile('utf8'))}finally{await fd.close()}
 const r=value as UploadRecord;if(!r||r.schemaVersion!==1||r.meetingId!==mid||r.uploadId!==id||!Number.isSafeInteger(r.totalBytes)||r.totalBytes<1||r.totalBytes>MAX_FILE_BYTES||!Number.isSafeInteger(r.offset)||r.offset<0||r.offset>r.totalBytes||!['uploading','finishing','finished','cancelled'].includes(r.status)||!Array.isArray(r.chunks)||r.chunks.length>512||typeof r.name!=='string'||!r.name||r.name.length>160||/[\\/\x00-\x1f]/.test(r.name)||typeof r.mimeType!=='string'||r.mimeType.length>160||/[\x00-\x1f]/.test(r.mimeType)||typeof r.requestId!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(r.requestId)||r.fingerprint!==sha(JSON.stringify([r.name,r.mimeType,r.totalBytes]))||r.uploadId!==`upload-${sha(JSON.stringify([mid,r.requestId])).slice(0,40)}`)reject('UPLOAD_CORRUPT','上传状态损坏，未批准原件')
 let offset=0;for(const c of r.chunks){if(c.offset!==offset||!Number.isSafeInteger(c.size)||c.size<1||c.size>FILE_CHUNK_BYTES||!/^[a-f0-9]{64}$/.test(c.sha256))reject('UPLOAD_CORRUPT','分片记录损坏');offset+=c.size}if(offset!==r.offset)reject('UPLOAD_CORRUPT','分片长度与记录不同');return r
}
async function writeRecord(r:UploadRecord){const path=recordPath(r.meetingId,r.uploadId);await guardOwnedFilePath(stateRoot(),path,false);try{const st=await lstat(path);if(!st.isFile()||st.nlink!==1)reject('UPLOAD_PATH_REJECTED','上传记录不是独立普通文件')}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}const tmp=path+'.'+randomUUID()+'.tmp',fd=await open(tmp,'wx',0o600);try{await fd.writeFile(JSON.stringify(r)+'\n');await fd.sync()}finally{await fd.close()}try{await guardOwnedFilePath(stateRoot(),directory(r.meetingId,r.uploadId));await rename(tmp,path)}finally{await unlink(tmp).catch(()=>{})}}
async function active(mid:string){const m=await requireActiveMeeting(stateRoot(),mid);if(m.archivedAt)reject('MEETING_ARCHIVED','会议已归档，不能上传新原件');return m}
async function scope<T>(mid:string,id:string,fn:()=>Promise<T>){return withMeetingActivity(stateRoot(),mid,()=>withMeetingLock(`file-upload:${stateRoot()}:${mid}:${id}`,async()=>{await active(mid);try{return await fn()}catch(e){if(e instanceof FileUploadRejected)throw e;if(/链接|越界|不是独立|身份变化/.test(String((e as Error).message)))reject('UPLOAD_PATH_REJECTED',String((e as Error).message));throw e}}))}
export async function beginFileUpload(_ctx:Context,mid:string,input:{requestId:string;name:string;mimeType:string;totalBytes:number}){
 if(typeof input.requestId!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(input.requestId))reject('INVALID_REQUEST_ID','上传请求标识非法')
 if(typeof input.name!=='string'||!input.name.trim()||input.name.length>160||/[\x00-\x1f]/.test(input.name))reject('INVALID_FILE_NAME','文件名称需有效且不超过160字符')
 if(!Number.isSafeInteger(input.totalBytes)||input.totalBytes<1||input.totalBytes>MAX_FILE_BYTES)reject('FILE_TOO_LARGE','完整原件需大于0且不超过256MiB')
 if(typeof input.mimeType!=='string'||input.mimeType.length>160||/[\x00-\x1f]/.test(input.mimeType))reject('INVALID_MIME_TYPE','原件类型无效')
 const name=input.name.replace(/[\\/]/g,'_'),mimeType=input.mimeType||'application/octet-stream',fingerprint=sha(JSON.stringify([name,mimeType,input.totalBytes])),id=`upload-${sha(JSON.stringify([mid,input.requestId])).slice(0,40)}`
 return scope(mid,id,async()=>{await ensureOwnedDirectory(stateRoot(),join(stateRoot(),mid,'uploads'));await ensureOwnedDirectory(stateRoot(),directory(mid,id));let existing:UploadRecord|undefined;try{existing=await readRecord(mid,id)}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}if(existing){if(existing.fingerprint!==fingerprint)reject('UPLOAD_REQUEST_CONFLICT','同上传请求已经用于不同原件');if(existing.status==='uploading'&&existing.offset===0){const payload=payloadPath(mid,id);try{await guardOwnedFilePath(stateRoot(),payload)}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;const fd=await open(payload,'wx',0o600);await fd.sync();await fd.close()}}return dto(existing)}
 if((await readdir(directory(mid,id))).length)reject('UPLOAD_PATH_REJECTED','新上传目录包含未绑定内容，拒绝接管或覆盖用户文件')
 const r:UploadRecord={schemaVersion:1,meetingId:mid,uploadId:id,requestId:input.requestId,fingerprint,name,mimeType,totalBytes:input.totalBytes,offset:0,status:'uploading',chunks:[]};await writeRecord(r);const payload=payloadPath(mid,id);await guardOwnedFilePath(stateRoot(),payload,false);const fd=await open(payload,'wx',0o600);await fd.sync();await fd.close();return dto(r)})
}
export async function appendFileUpload(_ctx:Context,mid:string,input:{uploadId:string;offset:number;data:string}){
 const id=uploadID(input.uploadId);if(!Number.isSafeInteger(input.offset)||input.offset<0||typeof input.data!=='string'||input.data.length>Math.ceil(FILE_CHUNK_BYTES/3)*4)reject('INVALID_CHUNK','分片offset或长度无效');const bytes=Buffer.from(input.data,'base64');if(!bytes.length||bytes.length>FILE_CHUNK_BYTES||bytes.toString('base64')!==input.data)reject('INVALID_CHUNK','分片需为不超过512KiB的完整base64字节')
 return scope(mid,id,async()=>{const r=await readRecord(mid,id);if(r.status==='cancelled')reject('UPLOAD_CANCELLED','本次上传已撤回');const old=r.chunks.find(c=>c.offset===input.offset),hash=sha(bytes),fd=await openOwnedFile(stateRoot(),payloadPath(mid,id),true)
 try{if(old){if(old.sha256!==hash||old.size!==bytes.length)reject('CHUNK_CONFLICT','同offset分片内容不同，拒绝覆盖');const stored=Buffer.alloc(old.size),read=await fd.read(stored,0,old.size,input.offset);if(read.bytesRead!==old.size||sha(stored)!==hash)reject('UPLOAD_CORRUPT','已收到分片实际字节改动或缺失');return dto(r)}
 if(r.status!=='uploading'||input.offset!==r.offset||input.offset+bytes.length>r.totalBytes||bytes.length!==Math.min(FILE_CHUNK_BYTES,r.totalBytes-r.offset))reject('CHUNK_OFFSET_CONFLICT','请按已确认offset顺序上传完整分片')
 const size=(await fd.stat()).size;if(size>r.offset){if(size!==r.offset+bytes.length)reject('UPLOAD_CORRUPT','未确认分片长度异常');const pending=Buffer.alloc(bytes.length),read=await fd.read(pending,0,pending.length,r.offset);if(read.bytesRead!==bytes.length||sha(pending)!==hash)reject('CHUNK_CONFLICT','上次未确认分片与重试字节不同，不覆盖')}else{if(size!==r.offset)reject('UPLOAD_CORRUPT','临时原件长度与offset不同');let written=0;while(written<bytes.length){const result=await fd.write(bytes,written,bytes.length-written,r.offset+written);if(!result.bytesWritten)throw Error('分片写入未完成');written+=result.bytesWritten}await fd.sync()}
 await guardOwnedFilePath(stateRoot(),payloadPath(mid,id));r.chunks.push({offset:r.offset,size:bytes.length,sha256:hash});r.offset+=bytes.length;await writeRecord(r);return dto(r)
 }finally{await fd.close()}})
}
export function projectFileAssetLocation(m:Meeting,asset:MeetingAsset):MeetingAsset{const ref=m.meetingFolder?.files.find(f=>f.kind==='asset'&&f.id===asset.id&&f.version===asset.version&&f.sha256===asset.sha256);return{...asset,storageLocation:ref?'meeting-folder':'internal-assets',...(ref?{fileReference:{fileId:ref.fileId,relativePath:ref.relativePath,folderPath:m.meetingFolder!.path}}:{}),...(asset.referenceOnly?{contentNote:'完整原件引用，内容未解析；不自动解压或把二进制注入模型。'}:{})}}
async function verifyPayload(r:UploadRecord){const fd=await openOwnedFile(stateRoot(),payloadPath(r.meetingId,r.uploadId)),hash=createHash('sha256'),buffer=Buffer.alloc(FILE_CHUNK_BYTES);try{const before=await fd.stat();if(before.size!==r.totalBytes)reject('UPLOAD_CORRUPT','完整原件长度不符');for(const chunk of r.chunks){const read=await fd.read(buffer,0,chunk.size,chunk.offset);const part=buffer.subarray(0,read.bytesRead);if(read.bytesRead!==chunk.size||sha(part)!==chunk.sha256)reject('UPLOAD_CORRUPT','已收到分片实际字节被改动，不能批准新hash');hash.update(part)}const after=await fd.stat();if(before.size!==after.size||before.mtimeMs!==after.mtimeMs||before.ctimeMs!==after.ctimeMs)reject('UPLOAD_CORRUPT','原件核验时发生改动');return{size:before.size,sha256:hash.digest('hex')}}finally{await fd.close()}}
export async function finishFileUpload(_ctx:Context,mid:string,input:{uploadId:string}):Promise<MeetingAsset>{const id=uploadID(input.uploadId);return scope(mid,id,async()=>{const r=await readRecord(mid,id);if(r.status==='cancelled')reject('UPLOAD_CANCELLED','上传已撤回，不批准文件');if(r.offset!==r.totalBytes)reject('UPLOAD_INCOMPLETE','原件未完整收到，不能批准');const verified=await verifyPayload(r)
 if(!r.asset){const assetId=`asset-${sha(JSON.stringify(['file-reference',verified.sha256,r.name,r.mimeType]))}`;r.asset=await reserveMeetingAssetVersion(mid,{id:assetId,name:r.name,mimeType:r.mimeType,bytes:r.totalBytes,sha256:verified.sha256,contentKind:'file',referenceOnly:true});r.status='finishing';await writeRecord(r)}
 const asset=r.asset,expectedId=`asset-${sha(JSON.stringify(['file-reference',verified.sha256,r.name,r.mimeType]))}`;if(asset.id!==expectedId||asset.name!==r.name||asset.mimeType!==r.mimeType||asset.sha256!==verified.sha256||asset.bytes!==verified.size||asset.referenceOnly!==true||asset.contentKind!=='file'||asset.text!==undefined||asset.image!==undefined||!Number.isSafeInteger(asset.version)||asset.version<1||!Number.isFinite(asset.createdAt)||asset.createdAt<=0)reject('UPLOAD_CORRUPT','冻结原件与实际字节或服务生成路径不同');await ensureOwnedDirectory(stateRoot(),join(stateRoot(),mid,'assets'));await copyOwnedFile(stateRoot(),payloadPath(mid,id),stateRoot(),join(stateRoot(),mid,'assets',asset.id),verified)
 const m=await mutateMeeting(stateRoot(),mid,async current=>{if(current.archivedAt)reject('MEETING_ARCHIVED','归档后不批准新原件');const old=current.assets?.find(a=>a.id===asset.id);if(old&&(old.sha256!==asset.sha256||old.bytes!==asset.bytes))reject('UPLOAD_CONFLICT','原件编号已用于不同内容');const synced=await syncMeetingAssetFile(current,old??asset,payloadPath(mid,id));return old?synced:{...synced,assets:[...(synced.assets??[]),asset]}})
 r.status='finished';await writeRecord(r);return projectFileAssetLocation(m,m.assets!.find(a=>a.id===asset.id)!)} )}
export async function cancelFileUpload(_ctx:Context,mid:string,input:{uploadId:string}){const id=uploadID(input.uploadId);return scope(mid,id,async()=>{const r=await readRecord(mid,id),m=await active(mid),approved=r.asset&&m.assets?.find(a=>a.id===r.asset!.id);if(approved)return{cancelled:true as const,approvedAssetId:approved.id};r.status='cancelled';await writeRecord(r);const path=payloadPath(mid,id);try{await guardOwnedFilePath(stateRoot(),path);const st=await lstat(path);if(!st.isFile()||st.nlink!==1)reject('UPLOAD_PATH_REJECTED','临时原件身份不同，不删除');await unlink(path)}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e}return{cancelled:true as const}})}
/** Trusted Host HTTP only. Activity remains admitted until the safe descriptor's stream closes. */
export async function openMeetingAssetDownload(mid:string,assetId:string){let resolve!:(value:{asset:MeetingAsset;stream:ReturnType<Awaited<ReturnType<typeof openOwnedFile>>['createReadStream']>})=>void,reject!:(error:unknown)=>void;const ready=new Promise<{asset:MeetingAsset;stream:ReturnType<Awaited<ReturnType<typeof openOwnedFile>>['createReadStream']>}>((yes,no)=>{resolve=yes;reject=no})
 void withMeetingActivity(stateRoot(),mid,async()=>{const m=await requireActiveMeeting(stateRoot(),mid),asset=m.assets?.find(a=>a.id===assetId);if(!asset||!/^asset-[a-f0-9]{64}$/.test(assetId))throw Error('原件尚未批准或文件标识非法');let stream
 if(m.meetingFolder){const ref=m.meetingFolder.files.find(f=>f.kind==='asset'&&f.id===assetId&&f.version===asset.version&&f.sha256===asset.sha256);if(!ref)throw Error('原件未批准到本会目录');stream=(await openMeetingDocumentDownload(m,ref.fileId)).stream}else{const fd=await openOwnedFile(stateRoot(),join(stateRoot(),mid,'assets',assetId));try{const verified=await hashFileHandle(fd);if(verified.sha256!==asset.sha256||verified.size!==asset.bytes)throw Error('原件校验失败：内容改动或损坏');stream=fd.createReadStream({start:0,autoClose:true})}catch(e){await fd.close();throw e}}
 const closed=new Promise<void>(yes=>{stream.once('close',yes);stream.once('error',()=>yes())});resolve({asset:projectFileAssetLocation(m,asset),stream});await closed}).catch(reject);return ready
}
