import {randomUUID} from 'node:crypto'
import type {Context} from '@deepseek-ai/cordis'
import {SessionId,type Session} from '@deepseek-ai/dsh-session'
import {createUserMessage,freezeMessage} from '@deepseek-ai/dsh-llm/message'
import {mutateMeeting,requireActiveMeeting,stateRoot,type Meeting} from './meetings.ts'
import {syncMeetingFolderInstructions} from './meeting-folder.ts'
import {withMeetingActivity} from './meeting-activity.ts'
import {memberEvidence} from './member-session-state.ts'
import {memberForBriefing,memberIsArchived} from './member-session.ts'
import {readStoredSession,sessionHistory} from './host-runtime.ts'
import type {MemberBriefing} from './member-briefing-types.ts'
const running=new WeakMap<object,Map<string,{sessionId:string;role:string;promise:Promise<Meeting>}>>()
function writable(m:Meeting,sid:string){if(m.archivedAt||m.deletion||!m.memberSessionIds.includes(sid)||m.secretary?.sessionId===sid)throw Error('会议已归档、删除或成员已离会；没有发送新简报')}
const text=(m:Meeting,role:string)=>{const f=m.meetingFolder;return `[圆桌会议「${m.title}」简报]\n会议说明：${m.description??''}\n你的职责：${role}${f?`\n本会目录：${f.path}\n说明入口：${f.instructionsRelativePath??'会议说明.md'}\n先用 meeting_file_index({meetingId:"${m.meetingId}"}) 获取已批准文件版本，再用 meeting_read_file({meetingId:"${m.meetingId}",fileId}) 只读实际内容；跨工作区也通过这些工具读取，不从路径猜测内容。`:'\n本会尚未关联工作目录，不宣称已读取文件。'}\n此简报仅介绍会议与资料，不是工作任务，不打断原窗口工作，不导出原窗口其他私聊。普通讨论按 meeting_reply_message 回传，不认领工作。任务卡生成按 meeting_propose_task_cards 回传，只准备不执行。只有主持人确认发布或明确启动环节后才按任务协议认领与提交正式结果。`}
const find=(m:Meeting,sid:string)=>m.memberBriefings?.find(b=>b.sessionId===sid)
async function receipt(ctx:Context,b:MemberBriefing){const stored=await readStoredSession(ctx,b.sessionId);if(stored.meta.createdAt!==b.sessionCreatedAt||stored.meta.cwd!==b.sessionCwd)throw Error('原成员会话身份已变化，不能确认或重投旧简报');const match=(v:unknown)=>{const m=v as {id?:unknown;source?:{kind?:string;plugin?:string};content?:{type?:string;text?:string}[]};return m?.id===b.hostMessageId&&m.source?.kind==='round-table'&&m.source.plugin==='dsh-round-table'&&m.content?.some(x=>x.type==='text'&&x.text===b.text)};return stored.events.some(e=>e.type==='user/message'?match((e.data as {message?:unknown})?.message??e.data):e.type==='agent/inbox/spliced'&&(e.data as {inserted?:unknown[]})?.inserted?.some(match))}
async function markDelivered(ctx:Context,mid:string,b:MemberBriefing){if(!await receipt(ctx,b))throw Error('简报送达尚待核实，保留原请求；不会自动重投');return mutateMeeting(stateRoot(),mid,m=>{const current=find(m,b.sessionId);if(!current||current.id!==b.id||!['sending','unknown','delivered'].includes(current.status))throw Error('原简报记录已变化，请核对');if(current.status!=='delivered'){current.status='delivered';current.deliveredAt??=Date.now();current.updatedAt=Date.now();delete current.error}m.briefedSessionIds=[...new Set([...(m.briefedSessionIds??[]),b.sessionId])];return m})}
async function execute(ctx:Context,mid:string,sid:string,role:string){return withMeetingActivity(stateRoot(),mid,async()=>{
 let m=await requireActiveMeeting(stateRoot(),mid),b=find(m,sid)
 if(!b&&(m.briefedSessionIds??[]).includes(sid))return m // Old authoritative acknowledgement never replays a briefing.
 if(b?.status==='delivered')return m
 writable(m,sid)
 if(b&&b.role!==role)throw Error('此成员原简报已冻结另一职责，请核对原请求后重试，不替换其正文')
 if(b?.status==='cancelled')throw Error('原简报等待已结束，不能自动重投')
 if(b&&['sending','unknown'].includes(b.status))return markDelivered(ctx,mid,b)
 if(!b){m=await mutateMeeting(stateRoot(),mid,async current=>{writable(current,sid);const old=find(current,sid);if(old){if(old.role!==role)throw Error('简报职责已变化');return current}if((current.briefedSessionIds??[]).includes(sid))return current;const evidence=await memberEvidence(ctx,sid);if(!evidence.header||!['ready','busy','unloaded'].includes(evidence.inspection.state)||typeof evidence.header.cwd!=='string')throw Error(evidence.inspection.reason??'原成员身份或状态无法确认，未准备新简报');const now=Date.now(),intent:MemberBriefing={id:`briefing-${randomUUID()}`,sessionId:sid,role,hostMessageId:String(createUserMessage({content:[{type:'text',text:'会议简报准备意图'}],source:{kind:'round-table',plugin:'dsh-round-table'}}).id),status:'prepared',sessionCreatedAt:evidence.header.createdAt,sessionCwd:evidence.header.cwd,createdAt:now,updatedAt:now};current.memberBriefings=[...(current.memberBriefings??[]),intent];current.memberRoles={...(current.memberRoles??{}),[sid]:role};return current});b=find(m,sid);if(!b)return m}
 if(b.status==='prepared'){m=await mutateMeeting(stateRoot(),mid,async current=>{writable(current,sid);const original=find(current,sid);if(!original||original.id!==b!.id||original.role!==role)throw Error('简报意图已变化');if(original.status!=='prepared')return current;const approved=await syncMeetingFolderInstructions({...current,memberRoles:{...(current.memberRoles??{}),[sid]:role}});const ready=find(approved,sid)!;ready.text=text(approved,role);ready.status='ready';ready.updatedAt=Date.now();delete ready.error;return approved});b=find(m,sid)!}
 if(['sending','unknown'].includes(b.status))return markDelivered(ctx,mid,b)
 if(b.status==='delivered')return m
 const originalEvidence=await memberEvidence(ctx,sid);if(!originalEvidence.header||!['ready','busy','unloaded'].includes(originalEvidence.inspection.state)||originalEvidence.header.createdAt!==b.sessionCreatedAt||originalEvidence.header.cwd!==b.sessionCwd)throw Error(originalEvidence.inspection.reason??'原成员身份与简报意图不符，拒绝恢复替代会话');
 const agent=await memberForBriefing(ctx,sid),stored=await readStoredSession(ctx,sid);if(String(agent.session.id)!==sid||stored.meta.createdAt!==agent.session.header.createdAt||stored.meta.cwd!==agent.session.header.cwd||stored.meta.createdAt!==b.sessionCreatedAt||stored.meta.cwd!==b.sessionCwd)throw Error('原会话身份不匹配，未发送简报');const last=stored.events.at(-1),live=last?sessionHistory(agent.session).find(e=>e.seq===last.seq):undefined;if(last&&(!live||live.type!==last.type||live.time!==last.time))throw Error('原会话状态过期，未发送简报');if(typeof agent.followup!=='function')throw Error('原宿主缺少FIFO接口，未发送简报')
 let admitted=false;m=await mutateMeeting(stateRoot(),mid,current=>{writable(current,sid);const original=find(current,sid);if(!original||original.id!==b!.id||original.status!=='ready')return current;if(ctx.agents.get(SessionId(sid))!==agent||memberIsArchived(ctx,sid))throw Error('原成员已归档或身份变化，未发送简报');original.status='sending';original.sessionCreatedAt=stored.meta.createdAt as number;original.sessionCwd=stored.meta.cwd;original.updatedAt=Date.now();admitted=true;return current});b=find(m,sid)!;if(!admitted)return markDelivered(ctx,mid,b)
 try{
  // The durable sending reservation precedes FIFO acceptance. A crash anywhere
  // after it only reconciles this exact message; it cannot authorize another send.
  if(ctx.agents.get(SessionId(sid))!==agent||memberIsArchived(ctx,sid))throw Error('原成员状态已变化，保留原简报等待核实')
  return await mutateMeeting(stateRoot(),mid,async latest=>{writable(latest,sid);const reserved=find(latest,sid);if(!reserved||reserved.id!==b!.id||reserved.status!=='sending')throw Error('原简报发送预约已变化，未重新发送');if(ctx.agents.get(SessionId(sid))!==agent||memberIsArchived(ctx,sid))throw Error('原成员状态已变化，保留原简报等待核实');const message=freezeMessage({...createUserMessage({content:[{type:'text',text:reserved.text!}],source:{kind:'round-table',plugin:'dsh-round-table'}}),id:reserved.hostMessageId as never});agent.followup(message);const sessions=ctx.get('sessions') as {flush(s:Session):Promise<boolean>}|undefined;if(!sessions||!await sessions.flush(agent.session)||!await receipt(ctx,reserved))throw Error('宿主尚未确认简报已持久化');reserved.status='delivered';reserved.deliveredAt??=Date.now();reserved.updatedAt=Date.now();delete reserved.error;latest.briefedSessionIds=[...new Set([...(latest.briefedSessionIds??[]),sid])];return latest})
 }catch(error){try{await mutateMeeting(stateRoot(),mid,current=>{const original=find(current,sid);if(original?.id===b!.id&&original.status==='sending'){original.status='unknown';original.error=`简报送达待核实：${error instanceof Error?error.message:String(error)}`;original.updatedAt=Date.now()}return current})}catch(cleanupError){throw new AggregateError([error,cleanupError],'简报原发送身份已保留，但投递或账本确认失败；请核对原请求，不会重投')}throw error}
})}
/** Explicit join authorization, serialized per meeting; no model or private-history export. */
export function ensureMemberBriefing(ctx:Context,mid:string,sid:string,role:string):Promise<Meeting>{if(typeof role!=='string'||!role.trim()||role.length>10000)throw Error('请输入有效会议职责');role=role.trim();let queue=running.get(ctx);if(!queue){queue=new Map();running.set(ctx,queue)}const key=`${stateRoot()}\0${mid}`,old=queue.get(key);if(old){if(old.sessionId===sid){if(old.role!==role)return Promise.reject(Error('原简报正在处理不同职责，请保留原请求'));return old.promise}return old.promise.then(()=>ensureMemberBriefing(ctx,mid,sid,role),()=>ensureMemberBriefing(ctx,mid,sid,role))}const promise=execute(ctx,mid,sid,role).finally(()=>{if(queue!.get(key)?.promise===promise)queue!.delete(key)});queue.set(key,{sessionId:sid,role,promise});return promise}
