import {assetInputText} from './asset-reference.ts'
import {createHash} from 'node:crypto'
import type {Context} from '@deepseek-ai/cordis'
import {SessionId} from '@deepseek-ai/dsh-session'
import {memberIsArchived} from './member-session.ts'
import {defineTool} from '@deepseek-ai/dsh-tools'
import {mutateMeeting,requireActiveMeeting,stateRoot,type Meeting} from './meetings.ts'
import {readApprovedMeetingAsset} from './meeting-files-sync.ts'
import {assertImageRecipients} from './image-preflight.ts'
import {newDiscussion,pumpDiscussions,replyDiscussion} from './discussion.ts'
import {meetingMessageStream,freezeRelease,pumpReleases} from './meeting-flow.ts'
import {writeMeetingDocument,readMeetingDocument,attachMeetingDocument,syncMeetingFolderIndex,meetingFolderSnapshot} from './meeting-folder.ts'
import type {TaskCard,TaskCardGeneration,TaskCardMeetingFields,TaskCardVersion,CardPublication} from './task-card-types.ts'
export class TaskCardRequestRejected extends Error{}
function rejectPrecondition<T>(fn:()=>T):T {try{return fn()}catch(error){throw new TaskCardRequestRejected(error instanceof Error?error.message:String(error))}}
async function rejectPreconditionAsync<T>(fn:()=>Promise<T>):Promise<T>{try{return await fn()}catch(error){throw new TaskCardRequestRejected(error instanceof Error?error.message:String(error))}}
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
const id=(v:unknown)=>{if(typeof v!=='string'||!/^[a-zA-Z0-9_-]{1,100}$/.test(v))throw new TaskCardRequestRejected('非法请求编号');return v}
const text=(v:unknown,label:string,max=100000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new TaskCardRequestRejected(`${label}不能为空且不能超过${max}字符`);return v.trim()}
const ids=(v:unknown)=>{if(!Array.isArray(v)||v.length>200||v.some(x=>typeof x!=='string'||!x))throw new TaskCardRequestRejected('成员或材料列表非法');return [...new Set(v)] as string[]}
const fields=(m:Meeting)=>m as Meeting&TaskCardMeetingFields
function active(m:Meeting){if(m.archivedAt||m.deletion)throw Error('会议已归档或删除，不能修改任务卡')}
function members(m:Meeting,values:string[]){if(!values.length||values.some(x=>!m.memberSessionIds.includes(x)||x===m.secretary?.sessionId))throw Error('请先@至少一位当前会议的原成员；秘书不可代写')}
function card(m:Meeting,cardId:string){const c=fields(m).taskCards?.find(x=>x.id===cardId);if(!c)throw Error('任务卡不存在');return c}
function currentVersion(c:TaskCard,expected:number){if(!Number.isInteger(expected)||expected!==c.version)throw Error('任务卡已更新，请保留当前正文并刷新后核对版本')}
function selections(m:Meeting,messageIds:string[],assetIds:string[]){const stream=meetingMessageStream(m);if(messageIds.some(x=>!stream.some(a=>a.id===x&&!a.previewOnly)))throw Error('引用的正式会议消息不存在');if(assetIds.some(x=>!m.assets?.some(a=>a.id===x)))throw Error('引用材料不存在');const inputs=messageIds.map(x=>structuredClone(stream.find(a=>a.id===x)!)),assets=ids([...assetIds,...inputs.flatMap(x=>x.assetIds??[])]);for(const x of assets){const a=m.assets?.find(a=>a.id===x);if(!a)throw Error('引用材料不存在');inputs.push({id:a.id,time:a.createdAt,sender:'user',kind:'message',text:assetInputText(a,m)})}return {inputs,assetIds:assets}}
async function assertCurrentFolder(m:Meeting){if(m.meetingFolder){const snapshot=await meetingFolderSnapshot(m);if(snapshot.integrity!=='ok')throw Error('本会目录、当前说明或已批准文件无法核验，请先处理再生成或发布新卡：'+snapshot.errors.join('；'))}}
async function assertApprovedInputs(m:Meeting,assetIds:string[]){for(const assetId of assetIds)await readApprovedMeetingAsset(m,assetId)}
const generationRules=`你是主持人已@的原成员，依据你实际收到的本会议上下文及本次明确引用的材料分析后续工作。不要补读、导出其他私聊，不宣称掌握未收到的全部会议内容；不要编造期限、预算、事实或未批准工作。每个待办返回一张独立任务卡，不合并不同事项。每张卡的Markdown正文必须详细包含：任务名称、目标与背景、具体工作、建议执行人、材料位置及版本、成果要求及保存位置、完成标准、依赖和待确认条件。建议执行人和你这个生成者是不同字段；不确定执行人可留空并在正文说明。没有待办返回空清单及真实原因。此请求仅准备任务卡，不认领、不执行、不提交正式工作结果，不消耗流程工作额度。必须用 meeting_propose_task_cards(meetingId,generationId,discussionId,items,emptyReason,requestId) 回传结构化卡片，而不是仅回复普通消息。每个成员只提交一次清单；同次重试使用相同requestId和内容。`
export interface GenerateTaskCardsInput {recipientIds:string[];instruction?:string;messageIds?:string[];assetIds?:string[]}
async function enqueue(ctx:Context,meetingId:string,input:GenerateTaskCardsInput,requestId:string,target?:{cardId:string;expectedVersion:number;note:string}){
 const rid=id(requestId),recipientIds=ids(input.recipientIds),messageIds=ids(input.messageIds??[]),assetIds=ids(input.assetIds??[]),extra=input.instruction??'';if(typeof extra!=='string'||extra.length>100000)throw Error('补充说明过长');const requestHash=hash({recipientIds,messageIds,assetIds,extra,target}),generationId=`cardgen-${rid}`;let receipt!:{generationId:string;discussionId:string}
 await mutateMeeting(stateRoot(),meetingId,m=>rejectPreconditionAsync(async()=>{const f=fields(m),old=f.taskCardGenerations?.find(g=>g.requestId===rid);if(old){if(old.requestHash!==requestHash)throw Error('原请求编号已用于另一份生成说明');receipt={generationId:old.id,discussionId:old.discussionId};return m}active(m);members(m,recipientIds);const plan=selections(m,messageIds,assetIds);await assertCurrentFolder(m);await assertImageRecipients(ctx,m,recipientIds,plan.assetIds);await assertApprovedInputs(m,plan.assetIds);let focus='';if(target){const c=card(m,target.cardId);currentVersion(c,target.expectedVersion);if(c.generatorSessionId!==recipientIds[0]||recipientIds.length!==1)throw Error('只能向这张卡的原生成者请求调整');focus=`\n只调整指定一张卡，返回恰好一项；不得重生成其他卡。\n卡片ID=${c.id}，原版本=${c.version}\n名称：${c.title}\n当前正文：\n${c.body}\n主持人调整意见：${target.note}\n晚返回的内容只作为建议版本等待用户采纳。`}
 const instruction=`【明确任务卡${target?'调整':'生成'}请求】\ngenerationId=${generationId}\n${generationRules}${focus}\n${extra?`主持人额外说明：${extra}`:'主持人没有额外正文，请依据你已收到的会议上下文如实分析。'}`,d=newDiscussion(m,{instruction,recipientIds,messageIds},plan,`card-${rid}`,requestHash),g:TaskCardGeneration={id:generationId,requestId:rid,requestHash,discussionId:d.id,kind:target?'adjust':'generate',recipientIds,instruction,userInstruction:extra,...(target?{adjustmentNote:target.note}:{}),messageIds,assetIds:plan.assetIds,assetVersions:plan.assetIds.map(id=>{const a=m.assets!.find(x=>x.id===id)!;return {id,version:a.version,sha256:a.sha256}}),createdAt:Date.now(),responses:[],...(target?{cardId:target.cardId,baseVersion:target.expectedVersion}:{})};if(instruction.length+JSON.stringify(plan.inputs).length>100000)throw Error('所选会议上下文过长，请拆分材料；没有投递');f.taskCardGenerations=[...(f.taskCardGenerations??[]),g];m.discussions=[...(m.discussions??[]),d];m.events.push({id:d.messageId,kind:'message',time:d.createdAt,by:'user',text:instruction,discussionId:d.id,assetIds:plan.assetIds,replyTo:messageIds});receipt={generationId:g.id,discussionId:d.id};return m}));await pumpDiscussions(ctx);return receipt
}
export const startTaskCardGeneration=(ctx:Context,mid:string,input:GenerateTaskCardsInput,rid:string)=>enqueue(ctx,mid,input,rid)
export async function adjustTaskCard(ctx:Context,mid:string,cardId:string,input:{expectedVersion:number;note:string},rid:string){const m=await requireActiveMeeting(stateRoot(),mid),c=rejectPrecondition(()=>card(m,cardId)),g=fields(m).taskCardGenerations?.find(g=>g.id===c.generationId);rejectPrecondition(()=>{if(g?.assetVersions?.some(a=>!m.assets?.some(x=>x.id===a.id&&x.version===a.version&&x.sha256===a.sha256)))throw Error('原卡引用材料版本已改变，请先核对，不静默使用新版')});return enqueue(ctx,mid,{recipientIds:[c.generatorSessionId],messageIds:g?.messageIds??[],assetIds:g?.assetIds??[]},rid,{cardId,expectedVersion:input.expectedVersion,note:text(input.note,'调整意见',10000)})}
export interface ProposedTaskCard {title:string;body:string;assigneeSessionId?:string}
export async function proposeTaskCards(ctx:Context,mid:string,generationId:string,discussionId:string,actor:{session:{id:unknown}},items:ProposedTaskCard[],emptyReason:string|undefined,rid:string){
 const requestId=id(rid),sid=String(actor.session.id);if(!Array.isArray(items)||items.length>100)throw Error('任务卡清单非法或超过100项');const clean=items.map(x=>({title:text(x?.title,'任务名称',200),body:text(x?.body,'任务卡正文'),...(x.assigneeSessionId?{assigneeSessionId:text(x.assigneeSessionId,'建议执行人',200)}:{})}));if(!clean.length)emptyReason=text(emptyReason,'无待办说明',10000);else if(emptyReason!==undefined)throw Error('有卡片时不应同时声明无待办');const payload=JSON.stringify({generationId,items:clean,emptyReason});if(payload.length>100000)throw Error('任务卡回传超过10万字符，请缩减本次清单');for(const c of clean){const required=[/目标|背景/,/具体工作|工作内容/,/执行|负责/,/材料|资料/,/成果/,/完成标准|验收/,/依赖|待确认/];if(required.some(r=>!r.test(c.body)))throw Error('任务卡正文需详细说明目标、具体工作、执行人、材料、成果、完成标准及依赖或待确认条件')}const requestHash=hash({items:clean,emptyReason});const before=await requireActiveMeeting(stateRoot(),mid),g=fields(before).taskCardGenerations?.find(x=>x.id===generationId);if(!g||g.discussionId!==discussionId||!g.recipientIds.includes(sid))throw Error('仅本次已@的原生成者可以回传');if(g.kind==='adjust'&&clean.length!==1)throw Error('指定卡片调整必须只返回这一张卡');if(clean.some(x=>x.assigneeSessionId&&!before.memberSessionIds.includes(x.assigneeSessionId)))throw Error('建议执行者不是当前会议成员');const previous=g.responses.find(x=>x.sessionId===sid);if(previous&&(previous.requestId!==requestId||previous.hash!==requestHash))throw Error('该成员已回传；重试必须使用原请求及清单，不得重生成成功项');
 // The original FIFO receipt and actor instance are checked by the ordinary reply protocol.
 await replyDiscussion(ctx,mid,discussionId,actor,payload,requestId);let cardIds:string[]=[]
 await mutateMeeting(stateRoot(),mid,m=>{active(m);const f=fields(m),generation=f.taskCardGenerations?.find(x=>x.id===generationId);if(!generation||generation.discussionId!==discussionId||!m.memberSessionIds.includes(sid)||ctx.agents.get(SessionId(sid))!==actor||memberIsArchived(ctx,sid))throw Error('生成请求或成员已失效');const old=generation.responses.find(x=>x.sessionId===sid);if(old){if(old.requestId!==requestId||old.hash!==requestHash)throw Error('回传清单冲突');cardIds=old.cardIds;return m}f.taskCards??=[];if(generation.kind==='adjust'){const c=card(m,generation.cardId!),proposalId=`proposal-${hash([generationId,sid,requestId]).slice(0,32)}`;c.proposals.push({id:proposalId,generationId,baseVersion:generation.baseVersion!,...clean[0]!,createdAt:Date.now()});cardIds=[c.id]}else{cardIds=clean.map((x,index)=>{const cid=`card-${hash([generationId,sid,index]).slice(0,32)}`,version:TaskCardVersion={version:1,...x,source:'generator',sourceRequestId:requestId,createdAt:Date.now()};f.taskCards!.push({id:cid,generationId,generatorSessionId:sid,...x,version:1,createdAt:Date.now(),versions:[version],proposals:[],operations:[]});return cid})}generation.responses.push({sessionId:sid,requestId,hash:requestHash,cardIds,...(emptyReason?{emptyReason}:{}),createdAt:Date.now()});return m});return {generationId,cardIds}
}
function amend(c:TaskCard,next:{title:string;body:string;assigneeSessionId?:string},source:TaskCardVersion['source'],rid:string){c.version++;c.title=next.title;c.body=next.body;if(next.assigneeSessionId)c.assigneeSessionId=next.assigneeSessionId;else delete c.assigneeSessionId;c.versions.push({version:c.version,...next,source,sourceRequestId:rid,createdAt:Date.now()})}
export async function editTaskCard(mid:string,cardId:string,input:{expectedVersion:number;title:string;body:string;assigneeSessionId?:string},rid:string){const requestId=id(rid),next={title:text(input.title,'任务名称',200),body:text(input.body,'正文'),...(input.assigneeSessionId?{assigneeSessionId:text(input.assigneeSessionId,'执行人',200)}:{})},requestHash=hash(input);let result!:TaskCard;await mutateMeeting(stateRoot(),mid,m=>rejectPrecondition(()=>{active(m);const c=card(m,cardId),old=c.operations.find(x=>x.requestId===requestId);if(old){if(old.hash!==requestHash)throw Error('修改请求编号已用于其他正文');result=c;return m}currentVersion(c,input.expectedVersion);if(next.assigneeSessionId&&!m.memberSessionIds.includes(next.assigneeSessionId))throw Error('执行人不在当前会议');amend(c,next,'user',requestId);c.operations.push({requestId,hash:requestHash,version:c.version});result=c;return m}));return result}
export async function adoptTaskCardProposal(mid:string,cardId:string,proposalId:string,expectedVersion:number,rid:string){const requestId=id(rid),requestHash=hash({proposalId,expectedVersion});let result!:TaskCard;await mutateMeeting(stateRoot(),mid,m=>rejectPrecondition(()=>{active(m);const c=card(m,cardId),old=c.operations.find(x=>x.requestId===requestId);if(old){if(old.hash!==requestHash)throw Error('采纳编号已用于其他建议');result=c;return m}currentVersion(c,expectedVersion);const p=c.proposals.find(x=>x.id===proposalId);if(!p||p.adoptedVersion)throw Error('建议不存在或已经采纳');if(p.baseVersion!==expectedVersion)throw Error('调整期间正文已改动，请先对照建议手动合并，不能覆盖新编辑');if(p.assigneeSessionId&&!m.memberSessionIds.includes(p.assigneeSessionId))throw Error('建议执行人已离会');amend(c,p,'adjustment',requestId);p.adoptedVersion=c.version;c.operations.push({requestId,hash:requestHash,version:c.version});result=c;return m}));return result}
export async function publishTaskCards(ctx:Context,mid:string,input:{cards:{cardId:string;version:number}[];execute?:boolean},rid:string){const requestId=id(rid);if(!Array.isArray(input.cards)||!input.cards.length||input.cards.length>100||new Set(input.cards.map(c=>c.cardId)).size!==input.cards.length||input.execute!==undefined&&typeof input.execute!=='boolean')throw Error('请选择有效且不重复的卡片');const execute=input.execute!==false,requestHash=hash({cards:input.cards,execute}),publicationId=`cardpub-${requestId}`;let result!:CardPublication
 await mutateMeeting(stateRoot(),mid,m=>rejectPreconditionAsync(async()=>{const f=fields(m),old=f.cardPublications?.find(x=>x.requestId===requestId);if(old){if(old.requestHash!==requestHash)throw Error('发布编号已用于其他选择或执行方式');result=old;return m}if(input.execute===false)throw Error('确认发布会通知责任成员执行，请勿使用只保存方式绕过发布含义');active(m);const frozen=input.cards.map(v=>{const c=card(m,v.cardId);currentVersion(c,v.version);if(f.cardPublications?.some(p=>p.cards.some(x=>x.cardId===c.id&&x.version===c.version)))throw Error('此卡片版本已批准发布，请查看原发布记录或修改为新版本');if(execute){if(!c.assigneeSessionId)throw Error('执行前请确认每张卡的责任成员');members(m,[c.assigneeSessionId]);if(m.releasePaused)throw Error('会议执行队列暂停，请先恢复')}const g=f.taskCardGenerations?.find(g=>g.id===c.generationId),assetVersions=g?.assetVersions??[];if(assetVersions.some(a=>!m.assets?.some(x=>x.id===a.id&&x.version===a.version&&x.sha256===a.sha256)))throw Error('任务卡引用材料版本已改变，请重新核对生成或修改，不能静默使用新材料');return {cardId:c.id,version:c.version,title:c.title,body:c.body,messageIds:[...(g?.messageIds??[])],assetIds:[...(g?.assetIds??[])],assetVersions:structuredClone(assetVersions),generatorSessionId:c.generatorSessionId,generatorName:m.memberNames?.[c.generatorSessionId]??'参会成员',...(c.assigneeSessionId?{assigneeName:m.memberNames?.[c.assigneeSessionId]??'参会成员'}:{}),...(c.assigneeSessionId?{assigneeSessionId:c.assigneeSessionId}:{})}});await assertCurrentFolder(m);for(const c of frozen){await assertImageRecipients(ctx,m,[c.assigneeSessionId!],c.assetIds);await assertApprovedInputs(m,c.assetIds)}result={id:publicationId,requestId,requestHash,createdAt:Date.now(),execute,status:'prepared',cards:frozen};f.cardPublications=[...(f.cardPublications??[]),result];return m}))
 if(result.status==='published'){const m=await requireActiveMeeting(stateRoot(),mid);for(const c of result.cards){for(const a of c.assetVersions??[]){const ref=m.meetingFolder?.files.find(f=>f.kind==='asset'&&f.id===a.id&&f.version===a.version&&f.sha256===a.sha256);if(!ref)throw Error('批准材料文件版本不可核验');await readMeetingDocument(m,ref.fileId)}const doc=await readMeetingDocument(m,c.fileId!);if(doc.ref.sha256!==c.sha256||doc.ref.version!==c.version)throw Error('发布文件与批准版本不一致')}return result}
 await mutateMeeting(stateRoot(),mid,async m=>{active(m);const p=fields(m).cardPublications!.find(x=>x.id===publicationId)!;if(p.status==='published'){result=p;return m}if(p.execute){if(m.releasePaused)throw Error('会议执行队列暂停');members(m,p.cards.map(c=>c.assigneeSessionId!))}for(const c of p.cards){await assertApprovedInputs(m,c.assetIds??[]);if(p.execute)await assertImageRecipients(ctx,m,[c.assigneeSessionId!],c.assetIds??[]);if(c.assetVersions?.some(a=>!m.assets?.some(x=>x.id===a.id&&x.version===a.version&&x.sha256===a.sha256)))throw Error('批准后材料版本已改变，未通知执行');const ref=await writeMeetingDocument(m,{id:c.cardId,kind:'task',version:c.version,name:c.title,text:`# ${c.title}\n\n批准版本：${c.version}\n生成成员：${c.generatorName??m.memberNames?.[c.generatorSessionId]??'参会成员'}（${c.generatorSessionId}）\n责任成员：${c.assigneeSessionId?`${c.assigneeName??m.memberNames?.[c.assigneeSessionId]??'参会成员'}（${c.assigneeSessionId}）`:'待确认'}\n发布记录：${p.id}\n\n${c.body}\n`,metadata:{cardId:c.cardId,publicationId:p.id,generatorSessionId:c.generatorSessionId,assigneeSessionId:c.assigneeSessionId??''}});m=attachMeetingDocument(m,ref);c.fileId=ref.fileId;c.relativePath=ref.relativePath;c.sha256=ref.sha256;if(p.execute){const releaseId=`card-release-${hash([p.id,c.cardId]).slice(0,32)}`;if(!m.releases?.some(r=>r.id===releaseId)){const instruction=`按已批准任务卡 v${c.version} 执行。\n会议目录：${(m as Meeting&{meetingFolder?:{path:string}}).meetingFolder?.path??'通过会议文件工具读取'}\n会议文件：${c.relativePath}\n文件编号：${c.fileId}\nSHA256：${c.sha256}\n通过 meeting_read_file(meetingId,fileId) 读取指定版本；无法读取时报告失败，不宣称已开始。\n\n${c.body}`;const released=freezeRelease(m,{id:releaseId,version:1,title:c.title,status:'draft',createdAt:Date.now(),instruction,messageIds:c.messageIds??[],recipientIds:[c.assigneeSessionId!],assetIds:c.assetIds??[],tasks:[]});m.releases=[...(m.releases??[]),released]}c.releaseId=releaseId}}p.status='published';p.publishedAt=Date.now();fields(m).cardPublications=fields(m).cardPublications!.map(x=>x.id===p.id?p:x);await syncMeetingFolderIndex(m);result=p;return m});if(result.execute)await pumpReleases(ctx);return result
}
export function registerTaskCardTools(ctx:Context){ctx.tools.register(defineTool({name:'meeting_propose_task_cards',description:'仅已@原生成成员回传本次任务卡清单或指定卡调整。每事项一张Markdown详细卡；准备工作不执行任务。',parameters:{meetingId:{type:'string',required:true},generationId:{type:'string',required:true},discussionId:{type:'string',required:true},requestId:{type:'string',required:true},items:{type:'array',required:true,items:{type:'object',additionalProperties:false,properties:{title:{type:'string',required:true},body:{type:'string',required:true},assigneeSessionId:{type:'string'}}}},emptyReason:{type:'string',description:'没有待办时必须说明，items留空'}},output:{schema:{type:'object',additionalProperties:false,properties:{generationId:{type:'string',required:true},cardIds:{type:'array',required:true,items:{type:'string'}}}},render:(_a,v)=>[{type:'text',text:`任务卡准备完成：${v.cardIds.length}项；尚未批准执行。`}]},async execute(args,exec){if(!exec.agent)throw Error('缺少真实生成成员');return proposeTaskCards(ctx,String(args.meetingId),String(args.generationId),String(args.discussionId),exec.agent,args.items as ProposedTaskCard[],args.emptyReason===undefined?undefined:String(args.emptyReason),String(args.requestId))}}))}

export function listPublishedTaskCards(meeting:Meeting){const f=fields(meeting);return (f.cardPublications??[]).filter(p=>p.status==='published').flatMap(p=>p.cards.map(c=>{const original=f.taskCards?.find(x=>x.id===c.cardId),generation=f.taskCardGenerations?.find(g=>g.id===original?.generationId);return {...structuredClone(c),id:c.cardId,publicationId:p.id,publishedAt:p.publishedAt,messageIds:[...(c.messageIds??generation?.messageIds??[])],assetIds:[...(c.assetIds??generation?.assetIds??[])],fileRef:{fileId:c.fileId!,relativePath:c.relativePath!,sha256:c.sha256!,version:c.version}}}))}

