import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import type {MeetingAsset} from '../meeting-flow-types.ts'
import {useScopedOperations} from './use-scoped-operations.ts'
import {uiButton as button,localScopeId} from './ui-state.ts'
import {downloadMeetingAsset} from './asset-upload-client.ts'
import {assetStyles} from './asset-style.ts'

function AssetTile({meetingId,asset,onRemove,disabled,compact}:{meetingId:string;asset:MeetingAsset;onRemove?:()=>void;disabled?:boolean;compact?:boolean}):React.ReactNode{
 const {meetingCall,isCurrent}=useScopedOperations(),[data,setData]=useState<string>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[retry,setRetry]=useState(0)
 const anchor=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDivElement>(null),returnFocus=useRef<HTMLElement|null>(null),[layer,setLayer]=useState<HTMLElement|null>(null)
 const owner=useRef(localScopeId()).current
 const [referenceMetadata,setReferenceMetadata]=useState<{fileReference?:{fileId?:string;relativePath?:string;folderPath?:string};storageLabel?:string;storageLocation?:string}>()
 const identity=asset.id+':'+asset.version+':'+asset.sha256
 useEffect(()=>{let current=true;setData(undefined);setError('');if(!asset.image||asset.referenceOnly)return;setBusy(true);void meetingCall(meetingId,'asset-read',{id:asset.id}).then(v=>{if(current&&isCurrent())setData(v.asset.data)}).catch(e=>{if(current&&isCurrent())setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(current&&isCurrent())setBusy(false)});return()=>{current=false}},[meetingId,identity,retry])
 useEffect(()=>{if(!open)return;setLayer(anchor.current?.closest('.rt-chat')?.querySelector<HTMLElement>('[data-rt-chat-floating-layer]')??null);const previously=typeof document==='undefined'?null:document.activeElement;returnFocus.current=typeof HTMLElement!=='undefined'&&previously instanceof HTMLElement?previously:null;const timer=setTimeout(()=>dialog.current?.querySelector<HTMLButtonElement>('button')?.focus(),0);return()=>{clearTimeout(timer);returnFocus.current?.focus()}},[open,layer])
 const show=async()=>{
  if(!isCurrent())return
  if(data!==undefined){setOpen(true);return}
  setBusy(true);setError('')
  try{const value=await meetingCall(meetingId,'asset-read',{id:asset.id});if(isCurrent()){if(asset.referenceOnly&&(value.asset.id!==asset.id||value.asset.sha256!==asset.sha256||value.asset.bytes!==asset.bytes))throw Error('引用元信息与批准版本不同，未打开其他版本');if(asset.referenceOnly)setReferenceMetadata(value.asset);else setData(value.asset.data);setOpen(true)}}catch(e){if(isCurrent())setError(e instanceof Error?e.message:String(e))}finally{if(isCurrent())setBusy(false)}
 }
 const close=()=>setOpen(false)
 const image=!!asset.image&&!asset.referenceOnly&&data!==undefined?`data:${asset.mimeType};base64,${data}`:undefined
 const overlay=open&&<div ref={dialog} role="dialog" aria-modal="true" aria-label={`附件预览 ${asset.name}`} className="rt-asset-overlay" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close()}else if(e.key==='Tab'){const controls=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button,[href],[tabindex="0"]')??[]),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><header><b>{asset.name} · v{asset.version}</b><button style={button} onClick={close}>关闭附件预览</button></header>{asset.referenceOnly?<section aria-label="完整文件引用"><p>完整原件已保存；未自动解压或解析，本次引用不向模型发送二进制内容。</p><p>{asset.name} · {(asset.bytes/1024/1024).toFixed(2)}MB · {asset.mimeType}</p><p>保存位置：{referenceMetadata?.fileReference?.folderPath?`${referenceMetadata.fileReference.folderPath}/${referenceMetadata.fileReference.relativePath}`:referenceMetadata?.fileReference?.relativePath??(referenceMetadata?.storageLocation==='internal-assets'?'本会资料档案（工作区目录尚未关联）':referenceMetadata?.storageLabel??'保存位置暂未核验')}</p><small>批准版本 v{asset.version} · SHA256 {asset.sha256}</small><p><button style={button} disabled={busy} onClick={()=>{if(!isCurrent())return;setBusy(true);void downloadMeetingAsset(meetingId,asset,owner,isCurrent).catch(e=>{if(isCurrent())setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(isCurrent())setBusy(false)})}}>下载此版本原件</button></p></section>:image?<img alt={`${asset.name} 原图 · v${asset.version}`} src={image} style={{maxWidth:'100%',maxHeight:'calc(100% - 70px)',objectFit:'contain'}}/>:<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',overflow:'auto'}}>{data===undefined?'正在读取…':new TextDecoder().decode(Uint8Array.from(atob(data),c=>c.charCodeAt(0)))}</pre>}<small>本会归档原件 · {asset.bytes}字节 · 版本{asset.version}；预览与移除草稿引用均不唤醒成员。</small></div>
 const remove=()=>{if(onRemove&&!disabled&&isCurrent())onRemove()}
 return <div ref={anchor} className={`rt-asset-tile ${compact?'compact':''}`} data-asset-preview={asset.id} data-asset-kind={asset.image?'image':'file'} onKeyDown={e=>{if(!onRemove||disabled||e.ctrlKey||e.metaKey||e.altKey||e.nativeEvent?.isComposing||e.keyCode===229)return;if(e.target instanceof HTMLElement&&e.target.closest('[role="dialog"]'))return;if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();e.stopPropagation();remove()}}}>
  <button type="button" className="rt-asset-preview" title={`${asset.name} · v${asset.version} · 点击预览`} aria-label={`预览${asset.image?'图片':'文件'} ${asset.name} · v${asset.version}`} disabled={busy} onClick={()=>{void show()}}>{asset.image?(image?<img alt={`${asset.name} 缩略图`} src={image}/>:<span className="rt-asset-loading">图片加载中…</span>):<><svg className="rt-asset-file-icon" viewBox="0 0 16 16" fill="none" aria-hidden="true"><rect x="3" y="2" width="10" height="12" rx="1.5" stroke="currentColor"/><path d="M5.5 5h5M5.5 8h5M5.5 11h3" stroke="currentColor"/></svg><span className="rt-asset-file-name">{asset.name}</span></>}</button>
  {onRemove&&<button type="button" className="rt-asset-remove" disabled={disabled} aria-label={`移除草稿附件 ${asset.name}`} title={`移除 ${asset.name} 的草稿引用`} onClick={remove}><svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="m3 3 6 6m0-6L3 9" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/></svg></button>}
  {busy&&<small role="status">正在读取原件…</small>}{error&&<p role="alert" className="rt-asset-error">预览未成功：{error} <button style={button} onClick={()=>{asset.image?setRetry(x=>x+1):void show()}}>重试读取</button></p>}
  {overlay&&(layer?createPortal(overlay,layer):overlay)}
 </div>
}
export function ChatAssetPreview({meetingId,assets,assetIds,onRemove,disabled,compact=false}:{meetingId:string;assets:MeetingAsset[];assetIds:string[];onRemove?:(id:string)=>void;disabled?:boolean;compact?:boolean}):React.ReactNode{
 const selected=[...new Set(assetIds)],ordered=[...selected.filter(id=>assets.find(a=>a.id===id)?.image),...selected.filter(id=>!assets.find(a=>a.id===id)?.image)]
 const tile=(id:string)=>{const asset=assets.find(a=>a.id===id);return asset?<AssetTile key={asset.id+':'+asset.version} meetingId={meetingId} asset={asset} disabled={disabled} compact={compact} onRemove={onRemove?()=>onRemove(id):undefined}/>:<span key={id} role="alert">引用的历史附件未找到，请核对资料来源。{onRemove&&<button style={button} disabled={disabled} onClick={()=>{if(!disabled)onRemove(id)}}>移除缺失引用</button>}</span>}
 return <div className={`rt-asset-list ${compact?'compact':''}`} aria-label={onRemove?'草稿附件':'消息附件'}><style>{assetStyles}</style>{compact?<><div className="rt-asset-images">{ordered.filter(id=>assets.find(a=>a.id===id)?.image).map(tile)}</div><div className="rt-asset-files">{ordered.filter(id=>!assets.find(a=>a.id===id)?.image).map(tile)}</div></>:ordered.map(tile)}</div>
}
