import {useEffect,useRef,useState} from 'react'
import type {MeetingFolder,MeetingFileRef} from '../meeting-folder-types.ts'
import {useScopedOperations} from './use-scoped-operations.ts'
import {uiButton as button,downloadText} from './ui-state.ts'
interface Snapshot {path:string;instructionsText?:string;instructionsPath?:string;integrity:'ok'|'invalid';errors:string[];files:(MeetingFileRef&{status?:string;text?:string})[]}
export function MeetingFolderPanel({meetingId,folder,folderError,archived,onChanged}:{meetingId:string;folder?:MeetingFolder;folderError?:string;archived:boolean;onChanged:()=>Promise<void>}){
 const {meetingCall,isCurrent}=useScopedOperations(),[snapshot,setSnapshot]=useState<Snapshot>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[query,setQuery]=useState(''),[preview,setPreview]=useState<{name:string;text?:string;image?:string;referenceOnly?:boolean}>()
 const checkEpoch=useRef(0)
 const check=async()=>{const epoch=++checkEpoch.current;try{const v=await meetingCall(meetingId,'meeting-folder-status');if(isCurrent()&&epoch===checkEpoch.current){setSnapshot(v.snapshot);setError('')}}catch(e){if(isCurrent()&&epoch===checkEpoch.current)setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{if(folder)void check()},[folder?.path,folder?.instructionsSha256,folder?.instructionsVersion,JSON.stringify(folder?.files)])
 const connect=async()=>{if(busy||archived||!isCurrent())return;setBusy(true);setError('');try{await meetingCall(meetingId,'meeting-folder-connect',{confirmed:true});if(isCurrent()){setConfirm(false);await onChanged();await check()}}catch(e){if(isCurrent())setError(e instanceof Error?e.message:String(e))}finally{if(isCurrent())setBusy(false)}}
 const read=async(ref:MeetingFileRef)=>{if(busy)return;setBusy(true);setError('');try{const {file}=await meetingCall(meetingId,'meeting-file-read',{fileId:ref.fileId});if(!isCurrent())return;setPreview({name:ref.name,referenceOnly:file.referenceOnly,text:file.referenceOnly?'完整原件引用，内容未解析；不自动解压或向模型传入二进制。保存位置：'+ref.relativePath+' · '+ref.size+'字节 · v'+ref.version+' · SHA256 '+ref.sha256:file.text,...(!file.referenceOnly&&file.data&&ref.mimeType?.startsWith('image/')?{image:`data:${ref.mimeType};base64,${file.data}`}:{})})}catch(e){if(isCurrent())setError(e instanceof Error?e.message:String(e))}finally{if(isCurrent())setBusy(false)}}
 return <section aria-label="本会工作区目录" style={{border:'1px solid var(--dsw-alias-border-l2)',borderRadius:8,padding:10}}><b>本会工作区目录</b>
  {snapshot?.instructionsText!==undefined&&<details><summary>当前批准的会议说明</summary><small>{snapshot.instructionsPath}</small><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{snapshot.instructionsText}</pre></details>}
  {folder?<><p style={{overflowWrap:'anywhere'}}>{folder.path}</p><p>原成员通过会议只读工具读取已核验版本；秘书使用实际读取的文本快照。任务发布、成果和纪要先写入此目录。</p><button style={button} disabled={busy} onClick={()=>void check()}>核对目录与文件</button>{snapshot&&<p role="status">{snapshot.integrity==='ok'?'已核对当前说明、索引和文件版本':'目录核验未通过，不能用于新执行'}{snapshot.errors.length?`：${snapshot.errors.join('；')}`:''}</p>}<input aria-label="搜索会议文件" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索材料、任务卡、成果或纪要"/>{folder.files.filter(f=>`${f.name} ${f.kind} ${f.relativePath}`.toLowerCase().includes(query.toLowerCase())).map(f=><div key={f.fileId} style={{paddingTop:8}}><button style={button} disabled={busy} onClick={()=>void read(f)}>{f.name} · v{f.version}</button><small style={{marginLeft:6}}>{f.relativePath}</small></div>)}</>:<><p>本会尚未关联目录。确认后会在原会议工作区建立稳定目录并复制已有材料、任务、成果与纪要，不通知成员执行。</p>{folderError&&<p role="alert">{folderError}</p>}<button style={button} disabled={busy||archived} onClick={()=>setConfirm(true)}>关联本会目录…</button></>}
  {confirm&&<div role="alertdialog" aria-label="确认关联会议目录"><p>保留原会议数据，在本会工作区保存历史版本；不启动任务或模型。</p><button style={button} disabled={busy} onClick={()=>void connect()}>确认关联并保存历史文件</button><button style={button} disabled={busy} onClick={()=>setConfirm(false)}>取消</button></div>}
  {preview&&<div aria-label="会议文件预览"><b>{preview.name}</b>{preview.image?<img alt={preview.name} src={preview.image} style={{maxWidth:'100%',maxHeight:360}}/>:<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:420,overflow:'auto'}}>{preview.text??'此版本为二进制文件'}</pre>}{preview.text!==undefined&&!preview.referenceOnly&&<button style={button} onClick={()=>downloadText(preview.name,preview.text!)}>保存文本副本</button>}<button style={button} onClick={()=>setPreview(undefined)}>关闭预览</button></div>}{error&&<p role="alert">{error}</p>}
 </section>
}
