import {useEffect,useRef,useState} from 'react'
import type {PublishCandidate,ReleaseDraft} from '../meeting-flow-types.ts'
import {useScopedOperations} from './use-scoped-operations.ts'
const style:React.CSSProperties={font:'inherit',padding:6,border:'1px solid var(--dsw-alias-border-l2)',borderRadius:7,background:'var(--dsw-alias-bg-base)',color:'inherit',maxWidth:'100%'}
export function PublishPanel({meetingId,members,releases,onChanged,initialTarget,open:controlledOpen,onClose}:{meetingId:string;members:{id:string;name:string}[];releases:ReleaseDraft[];onChanged:()=>Promise<void>;initialTarget?:{taskId:string;sessionId:string};open?:boolean;onClose?:()=>void}):React.ReactNode{
  const {meetingCall,isCurrent}=useScopedOperations()
  const [expanded,setOpen]=useState(!!initialTarget),[sessionId,setSession]=useState(initialTarget?.sessionId??''),[items,setItems]=useState<PublishCandidate[]>([]),[next,setNext]=useState<number>(),[selected,setSelected]=useState<PublishCandidate>(),[taskId,setTask]=useState(initialTarget?.taskId??''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string>()
  const modal=controlledOpen!==undefined,open=controlledOpen??expanded,[purpose,setPurpose]=useState<'meeting'|'task'>(initialTarget?'task':'meeting')
  const dialog=useRef<HTMLElement>(null),returnFocus=useRef<HTMLElement>()
  useEffect(()=>{if(!modal||!open)return;if(typeof document!=='undefined')returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:undefined;dialog.current?.focus();return()=>returnFocus.current?.focus()},[modal,open])
  const [query,setQuery]=useState(''),[excerpt,setExcerpt]=useState(''),[note,setNote]=useState('')
  const guard=useRef(false),request=useRef<string>()
  const clear=()=>{setSelected(undefined);setPreview(false);setExcerpt('');setNote('');request.current=undefined}
  const close=()=>{if(guard.current)return;setOpen(false);clear();onClose?.();returnFocus.current?.focus()}
  const onDialogKey=(event:React.KeyboardEvent<HTMLElement>)=>{if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab')return;const controls=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex="0"]');if(!controls?.length){event.preventDefault();dialog.current?.focus();return}const first=controls[0]!,last=controls[controls.length-1]!;if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){event.preventDefault();last.focus()}else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===dialog.current)){event.preventDefault();first.focus()}}
  const call=(action:string,body:object)=>meetingCall(meetingId,action,body)
  const run=async(fn:()=>Promise<void>)=>{if(guard.current||!isCurrent())return;guard.current=true;setBusy(true);setError(undefined);try{await fn()}catch(e){if(isCurrent())setError(String(e instanceof Error?e.message:e))}finally{guard.current=false;if(isCurrent())setBusy(false)}}
  const load=(before?:number)=>run(async()=>{clear();const v=await call('publish-candidates',{sessionId,...(before!==undefined?{before}:{})});if(!isCurrent())return;setItems(v.items);setNext(v.nextBefore)})
  const targetTask=modal&&purpose==='meeting'?'':taskId
  const publish=()=>run(async()=>{if(!selected||!preview||modal&&purpose==='task'&&!targetTask)return;request.current??=crypto.randomUUID();await call('publish-reply',{sessionId,seq:selected.seq,digest:selected.digest,requestId:request.current,confirmed:true,...(excerpt!==selected.text?{excerpt}:{}),...(note.trim()?{note}:{}),...(targetTask?{taskId:targetTask}:{})});if(!isCurrent())return;clear();setOpen(false);onClose?.();returnFocus.current?.focus();try{await onChanged()}catch(e){if(isCurrent())setError(`公开已接受，列表刷新失败，请刷新查看，无需重复公开：${String(e)}`)}})
  const tasks=releases.flatMap(r=>r.tasks.map(t=>({...t,instruction:r.instruction}))).filter(t=>t.toSessionId===sessionId&&t.attempts!==0&&['delivered','in_progress','uncertain','failed'].includes(t.status))
  if(modal&&!open)return null
  const content=<section ref={dialog} role={modal?'dialog':undefined} aria-modal={modal?true:undefined} aria-label={modal?'导入成员回复':undefined} tabIndex={modal?-1:undefined} onKeyDown={modal?onDialogKey:undefined} className={modal?'rt-import-dialog':undefined} style={{display:'flex',flexDirection:'column',gap:8,minWidth:0,fontSize:12,...(modal?{background:'var(--dsw-alias-bg-base)',border:'1px solid var(--dsw-alias-border-l2)',borderRadius:12,padding:16,width:'min(660px,100%)',maxHeight:'88vh',overflow:'auto',boxSizing:'border-box'} as const:{})}}>
    {modal?<header style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><h3 style={{margin:0}}>导入成员回复</h3><button style={style} disabled={busy} onClick={close}>取消导入</button></header>:<button style={style} disabled={busy} onClick={()=>{setOpen(!open);clear()}}>{open?'关闭人工发布':'从原会话发布 / 补交结果'}</button>}
    {open&&<>
      <p style={{margin:0}}>{modal?'从成员原窗口选择回复，加入本会资料；不会通知其他成员。打开此窗口不会读取原会话，请先选择成员并主动读取。':'只读取你选择的原会话回复；先预览再确认。'}不会自动公开思考或工具日志。单条超过 10 万字符的回复不列入候选。</p>
      <select aria-label="来源成员" style={style} value={sessionId} disabled={busy} onChange={e=>{setSession(e.target.value);setItems([]);setNext(undefined);setTask('');clear()}}><option value="">选择来源成员</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>
      <button style={style} disabled={busy||!sessionId} onClick={()=>{void load()}}>读取近期回复</button>
      <input aria-label="搜索原回复" style={style} value={query} onChange={e=>setQuery(e.target.value)} placeholder="在本页回复中搜索"/>
      <div style={{maxHeight:240,overflow:'auto'}}>{items.filter(item=>!query||item.text.includes(query)).map(item=><label key={item.seq} style={{display:'block',marginBottom:7,overflowWrap:'anywhere'}}><input type="radio" name={modal?`import-candidate-${meetingId}`:`publish-${meetingId}`} disabled={busy} checked={selected?.seq===item.seq} onChange={()=>{clear();setSelected(item);setExcerpt(item.text)}}/>{new Date(item.time).toLocaleString()} · #{item.seq}<p style={{margin:0,whiteSpace:'pre-wrap'}}>{item.text.length>250?`${item.text.slice(0,250)}…（预览可看全文）`:item.text}</p></label>)}</div>
      {sessionId&&!items.length&&<span>尚无候选；点击读取，或选择其他成员。</span>}
      {next!==undefined&&<button style={style} disabled={busy} onClick={()=>{void load(next)}}>更早回复</button>}
      {modal?<fieldset style={{border:'1px solid var(--dsw-alias-border-l2)',borderRadius:8,padding:10}}><legend>这份回复用于</legend><label style={{display:'block'}}><input type="radio" name={`import-purpose-${meetingId}`} aria-label="加入本会资料" checked={purpose==='meeting'} disabled={busy} onChange={()=>{setPurpose('meeting');setPreview(false);request.current=undefined}}/>加入本会资料 · 不通知其他成员</label><label style={{display:'block',marginTop:7}}><input type="radio" name={`import-purpose-${meetingId}`} aria-label="补交工作任务结果" checked={purpose==='task'} disabled={busy} onChange={()=>{setPurpose('task');setPreview(false);request.current=undefined}}/>补交工作任务结果 · 提交后仍需主持人验收</label>{purpose==='task'&&<select aria-label="补交到任务" style={{...style,width:'100%',marginTop:8}} value={taskId} disabled={busy} onChange={e=>{setTask(e.target.value);setPreview(false);request.current=undefined}}><option value="">选择这位成员的任务</option>{tasks.map(t=><option key={t.taskId} value={t.taskId}>{t.instruction.slice(0,70)}</option>)}</select>}{purpose==='task'&&!tasks.length&&<p>这位成员没有可补交的任务。可改为加入本会资料。</p>}</fieldset>:<select aria-label="发布用途" style={style} value={taskId} disabled={busy} onChange={e=>{setTask(e.target.value);setPreview(false);request.current=undefined}}><option value="">发布为独立会议消息</option>{tasks.map(t=><option key={t.taskId} value={t.taskId}>补交：{t.instruction.slice(0,35)} · {t.taskId}</option>)}</select>}
      <button style={style} disabled={busy||!selected||modal&&purpose==='task'&&!taskId} onClick={()=>setPreview(true)}>{modal?'预览将加入的内容':'预览将公开的内容'}</button>
      {selected&&<><label>公开全文或连续片段<textarea aria-label="公开片段" rows={4} style={{...style,width:'100%',boxSizing:'border-box'}} value={excerpt} onChange={e=>{setExcerpt(e.target.value);setPreview(false);request.current=undefined}}/></label><label>主持人补充（单独标注）<textarea aria-label="主持人补充" rows={2} style={{...style,width:'100%',boxSizing:'border-box'}} value={note} onChange={e=>{setNote(e.target.value);setPreview(false);request.current=undefined}}/></label></>}
      {preview&&selected&&<div role="region" aria-label="人工发布确认" style={{border:'1px solid var(--dsw-alias-border-l2)',padding:8,overflowWrap:'anywhere'}}>
        <b>{targetTask?'补交到任务':'加入本会资料'} · 来源：{members.find(m=>m.id===sessionId)?.name}原窗口 · 回复 #{selected.seq}</b>{targetTask&&<p>任务：{tasks.find(t=>t.taskId===targetTask)?.instruction}。补交是提交结果，尚不代表验收通过。</p>}
        <p style={{whiteSpace:'pre-wrap'}}>{excerpt}{note.trim()?`\n\n【主持人补充】\n${note}`:''}</p>
        <p>确认后会成为正式会议资料，可供后续选用和秘书整理；不会通知或唤醒其他成员。原回复身份和内容校验保留。</p>
        <button style={style} disabled={busy} onClick={()=>{void publish()}}>{modal?targetTask?'确认导入并补交':'确认加入本会资料':`确认公开${taskId?'并补交':''}`}</button>
        <button style={style} disabled={busy} onClick={()=>setPreview(false)}>取消预览</button>
      </div>}
    </>}
    {error&&<p role="alert">{error}</p>}
  </section>
  return modal?<div className="rt-import-overlay" style={{position:'fixed',inset:0,zIndex:110,display:'grid',placeItems:'center',background:'rgba(0,0,0,.28)',padding:16}}>{content}</div>:content
}
