import {workflowSchemaSupported} from '../workflow-types.ts'
import {useEffect,useRef,useState} from 'react'
import type {MeetingMessage,ReleaseDraft,ReleaseTask,MeetingAsset} from '../meeting-flow-types.ts'
import type {WorkflowState} from '../workflow-types.ts'
import type {TaskCardMeetingFields} from '../task-card-types.ts'
import {taskNeedsAction,reviewState,revisionChild} from '../task-review.ts'
import {TaskRecovery} from './TaskRecovery.tsx'
import {RevisionPanel} from './RevisionPanel.tsx'
import {PublishPanel} from './PublishPanel.tsx'
import {ChatDiscussion} from './ChatDiscussion.tsx'
import {TaskCardsPanel} from './TaskCardsPanel.tsx'
import {LegacyTaskRecovery} from './LegacyTaskRecovery.tsx'
import {useCardGeneration} from './use-card-generation.ts'
import {useScopedOperations} from './use-scoped-operations.ts'
import {uiButton as button} from './ui-state.ts'
export interface MemberStatus {connected:boolean;running:boolean;pending:boolean;blockers:{meetingId:string;title:string;taskId:string;instruction:string}[];availability?:{state:string;reason?:string;workspaceId?:string;cwd?:string}}
interface Props extends TaskCardMeetingFields {meetingId:string;messages?:MeetingMessage[];releases?:ReleaseDraft[];paused?:boolean;archived?:boolean;members:{id:string;name:string}[];workflow?:WorkflowState;names?:Record<string,string>;memberStatus?:Record<string,MemberStatus>;assets?:MeetingAsset[];templates?:{id:string;title:string;instruction:string;recipientIds:string[]}[];view?:string;focusTask?:{id:string;nonce:number};onChanged:()=>Promise<void>;onViewChange?:(v:string)=>void;onOpenSession?:(id:string)=>void;onJumpMeeting?:(id:string)=>void;discussions?:import('../discussion-types.ts').DiscussionRecord[];taskModal?:boolean;onCloseTask?:()=>void;onOpenMember?:(id?:string,taskId?:string)=>void}
const labels:Record<string,string>={queued:'等待投递',offline:'原会话恢复或投递需处理',delivering:'正在投递',uncertain:'投递待核实',delivered:'等待正式结果',in_progress:'本会任务执行中',completed:'结果已提交',failed:'执行失败',cancelled:'已结束'}
export function ReleasePanel({meetingId,messages=[],releases=[],paused=false,archived=false,members,workflow,names={},memberStatus={},assets=[],view='discussion',focusTask,onChanged,onViewChange,onOpenSession,onJumpMeeting,discussions=[],taskModal=false,onCloseTask,onOpenMember,taskCards=[],taskCardGenerations=[],cardPublications=[]}:Props){
 const {meetingCall,isCurrent}=useScopedOperations(),guard=useRef(false)
 const [cardsOpen,setCardsOpen]=useState(false),[filter,setFilter]=useState('attention'),[limit,setLimit]=useState(40),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reference,setReference]=useState<MeetingMessage>(),[publishOpen,setPublishOpen]=useState(false),[supplement,setSupplement]=useState<{taskId:string;sessionId:string;nonce:number}>(),[revisionTarget,setRevisionTarget]=useState<string>(),[confirmation,setConfirmation]=useState<{action:string;body:object;text:string}>()
 const generation=useCardGeneration(meetingId,onChanged,()=>setCardsOpen(true))
 const activeRun=workflow&&workflowSchemaSupported(workflow.schemaVersion)?workflow.runs.find(r=>r.status==='active'):undefined,revisionTask=releases.flatMap(r=>r.tasks).find(t=>t.taskId===revisionTarget)
 const name=(id:string)=>id==='user'?'主持人':id==='secretary'?'秘书':members.find(m=>m.id===id)?.name??names[id]??'已离会成员'
 const run=async(fn:()=>Promise<void>)=>{if(guard.current||!isCurrent())return;guard.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(isCurrent())setError(e instanceof Error?e.message:String(e))}finally{guard.current=false;if(isCurrent())setBusy(false)}}
 const call=(action:string,body:object)=>run(async()=>{await meetingCall(meetingId,action,body);if(isCurrent())await onChanged()})
 const showReference=(id:string)=>{const m=messages.find(m=>m.id===id);if(m)setReference(m);else void run(async()=>{const v=await meetingCall(meetingId,'lookup-message',{id});if(isCurrent())setReference(v.message)})}
 const visible=[...releases].reverse().filter(r=>filter==='all'||r.status==='draft'||r.tasks.some(t=>taskNeedsAction({releases},t)))
 useEffect(()=>{if(!focusTask)return;setFilter('all');setLimit(releases.length);const timer=setTimeout(()=>{[...document.querySelectorAll('[data-release-task]')].find(n=>n.getAttribute('data-release-task')===focusTask.id)?.scrollIntoView({block:'center'})},60);return()=>clearTimeout(timer)},[focusTask?.nonce])
 return <section data-meeting-release-panel="" style={{display:'flex',flexDirection:'column',gap:10,fontSize:13,minWidth:0,...(view==='discussion'?{flex:1,minHeight:0}:{})}}>
  {error&&<p role="alert">{error}</p>}{generation.error&&<p role="alert">{generation.error}</p>}{generation.notice&&<p role="status">{generation.notice}</p>}{generation.pending&&<p role="alert">任务卡生成原请求待核实。<button style={button} disabled={generation.busy} onClick={generation.retry}>核对并重试原生成请求</button></p>}
  <LegacyTaskRecovery readOnly={archived} meetingId={meetingId} onChanged={onChanged}/>
  {reference&&<aside aria-label="引用原文"><b>{name(reference.sender)}</b><p style={{whiteSpace:'pre-wrap'}}>{reference.text}</p><button style={button} onClick={()=>setReference(undefined)}>关闭引用</button></aside>}
  {view==='discussion'&&<ChatDiscussion discussions={discussions} onOpenMember={onOpenMember} onCreateTask={d=>{if(!archived&&!generation.busy)generation.begin(d)}} meetingId={meetingId} messages={messages} releases={releases} members={members} assets={assets} names={names} memberStatus={memberStatus} draftRunIds={workflow&&workflowSchemaSupported(workflow.schemaVersion)?workflow.runs.map(r=>r.id):[]} run={activeRun} paused={paused} archived={archived} onChanged={onChanged} onNavigate={onViewChange} onOpenSession={onOpenSession} onPrepareTask={()=>setError('')} onSupplement={t=>setSupplement({taskId:t.taskId,sessionId:t.toSessionId,nonce:Date.now()})} onPublish={()=>setPublishOpen(true)}/>}
  {(publishOpen||supplement)&&<PublishPanel open={true} onClose={()=>{setPublishOpen(false);setSupplement(undefined)}} meetingId={meetingId} members={members} releases={releases} onChanged={onChanged} initialTarget={supplement}/>}
  <TaskCardsPanel readOnly={archived} meetingId={meetingId} open={taskModal||cardsOpen} onClose={()=>{setCardsOpen(false);onCloseTask?.()}} cards={taskCards} generations={taskCardGenerations} publications={cardPublications} discussions={discussions} members={members} onChanged={onChanged} onOpenMember={onOpenMember}/>
  {view==='tasks'&&<div aria-label="工作执行记录"><div><button style={button} onClick={()=>setCardsOpen(true)}>查看生成任务卡</button><button style={button} disabled={busy||archived} onClick={()=>void call('release-pause',{paused:!paused})}>{paused?'恢复投递队列':'暂停后续投递'}</button><select aria-label="任务筛选" value={filter} onChange={e=>setFilter(e.target.value)}><option value="attention">待处理与待验收</option><option value="all">全部任务</option></select></div>
   {!visible.length&&<p>没有待处理工作。生成任务卡请在讨论区 @原成员。</p>}
   {visible.slice(0,limit).map(r=><article key={r.id} data-release-id={r.id} style={{border:'1px solid var(--dsw-alias-border-l2)',padding:10,borderRadius:10,marginTop:8,overflowWrap:'anywhere'}}><b>{r.title??r.instruction.slice(0,55)} · {r.status==='draft'?'旧版本待放行记录':r.recipientIds.map(name).join('、')}</b>{r.status==='draft'&&<p>此历史草稿可查看和复制；需要后续工作时，请由原成员生成新卡并核对发布。</p>}
    {r.tasks.map(t=><section key={t.taskId} data-release-task={t.taskId} style={{paddingTop:8,borderTop:'1px solid var(--dsw-alias-border-l2)'}}><b>{name(t.toSessionId)} · {labels[t.status]}{t.status==='completed'?` · ${reviewState({releases},t)}`:''}</b><TaskRecovery task={t}/>{t.error&&<p>{t.error}</p>}{t.closedReason&&<p>结束说明：{t.closedReason}</p>}{t.result&&<p style={{whiteSpace:'pre-wrap'}}>{t.result.slice(0,220)}{t.result.length>220?'…':''}</p>}
     {t.status==='queued'&&memberStatus[t.toSessionId]?.blockers.filter(b=>b.taskId!==t.taskId).map(b=><p key={b.taskId}>等待「{b.title}」<button style={button} onClick={()=>onJumpMeeting?.(b.meetingId)}>查看阻塞会议</button></p>)}
     <div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{t.resultMessageId&&<button style={button} onClick={()=>showReference(t.resultMessageId!)}>查看结果与来源</button>}{['delivered','in_progress','uncertain','failed'].includes(t.status)&&t.attempts!==0&&<button style={button} disabled={archived} onClick={()=>setSupplement({taskId:t.taskId,sessionId:t.toSessionId,nonce:Date.now()})}>人工补交</button>}{['offline','uncertain'].includes(t.status)&&<button style={button} disabled={busy||paused||archived} onClick={()=>{if(t.status==='uncertain')setConfirmation({action:'retry-release',body:{taskId:t.taskId,allowDuplicate:true},text:'原消息可能已送达，请核对原窗口后确认；重试可能重复执行。'});else void call('retry-release',{taskId:t.taskId})}}>重试投递</button>}{!['completed','cancelled'].includes(t.status)&&<button style={button} disabled={busy} onClick={()=>setConfirmation({action:'close-task',body:{taskId:t.taskId,confirmed:true},text:'结束这项会议等待；原窗口工作继续，晚到结果不重新打开本任务。'})}>结束本会等待</button>}<button style={button} onClick={()=>onOpenSession?.(t.toSessionId)}>打开原窗口</button>{t.status==='completed'&&<><button style={button} disabled={busy||archived||t.review==='accepted'||!!revisionChild({releases},t)} onClick={()=>void call('review-task',{taskId:t.taskId,review:'accepted'})}>验收通过</button><button style={button} disabled={busy||archived||!!revisionChild({releases},t)} onClick={()=>void run(async()=>{await meetingCall(meetingId,'review-task',{taskId:t.taskId,review:'changes_requested',note:t.reviewNote??''});if(isCurrent()){await onChanged();setRevisionTarget(t.taskId)}})}>要求修改</button></>}</div><details><summary>投递记录</summary><p>尝试 {t.attempts} 次 · 更新 {new Date(t.updatedAt).toLocaleString()} · 来源 {t.resultSource?.kind==='manual'?'人工补交':t.resultSource?.kind==='agent'?'Agent提交':'旧记录未标注'}</p></details></section>)}
    <details><summary>要求与输入原文</summary><pre style={{whiteSpace:'pre-wrap'}}>{r.instruction}</pre>{(r.inputs??messages.filter(m=>r.messageIds.includes(m.id))).map(m=><details key={m.id}><summary>{name(m.sender)}：{m.text.slice(0,60)}</summary><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p></details>)}</details></article>)}{visible.length>limit&&<button style={button} onClick={()=>setLimit(n=>n+40)}>显示更多任务</button>}</div>}
  {revisionTask&&<RevisionPanel key={revisionTask.taskId} meetingId={meetingId} task={revisionTask} memberName={name(revisionTask.toSessionId)} onChanged={onChanged} onClose={()=>setRevisionTarget(undefined)}/>}{confirmation&&<div role="alertdialog" aria-label="确认任务操作"><p>{confirmation.text}</p><button style={button} disabled={busy} onClick={()=>{void call(confirmation.action,confirmation.body);setConfirmation(undefined)}}>确认</button><button style={button} onClick={()=>setConfirmation(undefined)}>取消</button></div>}
 </section>
}
