import {useEffect,useRef,useState} from 'react'
import type {TaskCard,TaskCardGeneration,CardPublication} from '../task-card-types.ts'
import type {DiscussionRecord} from '../discussion-types.ts'
import {scopedLocal,localScopeId,uiButton as button,uiInput as input} from './ui-state.ts'
interface Props {meetingId:string;open:boolean;readOnly?:boolean;onClose:()=>void;cards?:TaskCard[];generations?:TaskCardGeneration[];publications?:CardPublication[];discussions?:DiscussionRecord[];members:{id:string;name:string}[];onChanged:()=>Promise<void>;onOpenMember?:(id:string)=>void}
interface Editor {cardId:string;expectedVersion:number;title:string;body:string;assigneeSessionId:string;note:string}
interface Pending {requestId:string;action:string;body:Record<string,unknown>;label:string}
/** The key fences late responses and drafts when switching meetings or DSH homes. */
export function TaskCardsPanel(props:Props){const scope=localScopeId();return props.open?<TaskCardsDialog key={`${scope??'unknown'}:${props.meetingId}`} {...props}/>:null}
export function TaskCardsDialog({meetingId,readOnly=false,onClose,cards=[],generations=[],publications=[],discussions=[],members,onChanged,onOpenMember}:Props){
 const scope=useRef(localScopeId()).current,{readLocal,writeLocal,meetingCall}=scopedLocal(scope),draftKey=`task-cards-editor.${meetingId}`,pendingKey=`task-cards-pending.${meetingId}`
 const [editor,setEditor]=useState<Editor|undefined>(()=>readLocal(draftKey,undefined)),[selected,setSelected]=useState<string[]>([]),[pending,setPending]=useState<Pending|undefined>(()=>readLocal(pendingKey,undefined)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[approval,setApproval]=useState<TaskCard[]>([]),[notice,setNotice]=useState('')
 const guard=useRef(false),alive=useRef(true),dialog=useRef<HTMLDivElement>(null),focusReturn=useRef<HTMLElement>()
 useEffect(()=>{alive.current=true;if(typeof document!=='undefined'){focusReturn.current=document.activeElement instanceof HTMLElement?document.activeElement:undefined;dialog.current?.focus()}return()=>{alive.current=false;focusReturn.current?.focus()}},[])
 const name=(id:string|undefined)=>members.find(x=>x.id===id)?.name??(id?'已离会成员':'待确认')
 const batch=(c:TaskCard)=>{const n=generations.filter(g=>g.kind==='generate').findIndex(g=>g.id===c.generationId);return n<0?'历史生成':`第${n+1}次生成`}
 const edit=(next:Editor)=>{if(readOnly||guard.current||pending)return;if(!writeLocal(draftKey,next)){setError('无法保存本地编辑，请保留正文；尚未发送修改');return}setEditor(next);setNotice('')}
 const choose=(c:TaskCard)=>{if(readOnly){setEditor({cardId:c.id,expectedVersion:c.version,title:c.title,body:c.body,assigneeSessionId:c.assigneeSessionId??'',note:''});return}if(editor&&(editor.title!==cards.find(x=>x.id===editor.cardId)?.title||editor.body!==cards.find(x=>x.id===editor.cardId)?.body||editor.assigneeSessionId!==(cards.find(x=>x.id===editor.cardId)?.assigneeSessionId??'')||!!editor.note.trim())){setError('当前正文尚未保存，请先保存本卡；切换不会覆盖它');return}edit({cardId:c.id,expectedVersion:c.version,title:c.title,body:c.body,assigneeSessionId:c.assigneeSessionId??'',note:''})}
 const send=async(request:Pending)=>{if(readOnly||guard.current)return;guard.current=true;setBusy(true);setError('');try{const result=await meetingCall(meetingId,request.action,{...request.body,requestId:request.requestId});let next:Editor|undefined;if(request.action==='task-card-edit'||request.action==='task-card-adopt'){const c=(result.card??result) as TaskCard;if(!c.id||!c.version)throw Error('服务器修改回执缺少任务卡版本');next={cardId:c.id,expectedVersion:c.version,title:c.title,body:c.body,assigneeSessionId:c.assigneeSessionId??'',note:''};if(!writeLocal(draftKey,next))throw Error('修改已响应但本地正文未能保存，保留原请求核对')}if(!writeLocal(pendingKey,undefined))throw Error('操作已响应，但本地回执未能收尾；请用原请求核对');if(alive.current){setPending(undefined);if(next)setEditor(next);setNotice(request.action==='task-card-publish'?'选定卡片已发布，已进入责任成员通知队列；投递与执行状态见成员工作日志。':request.label+'已记录。生成或调整不会自动执行任务。');setConfirm(false);await onChanged()}}catch(e){const x=e as Error&{requestState?:string};if(x.requestState==='rejected'&&writeLocal(pendingKey,undefined)&&alive.current)setPending(undefined);if(alive.current)setError(x.message+(x.requestState==='rejected'?'':'；结果待核实，请保留原请求重试，勿新建同次操作'))}finally{guard.current=false;if(alive.current)setBusy(false)}}
 const begin=(action:string,body:Record<string,unknown>,label:string)=>{if(readOnly||guard.current||pending)return;const next={requestId:crypto.randomUUID(),action,body:structuredClone(body),label};if(!writeLocal(pendingKey,next)){setError('本地存储不可用，无法保留原请求；尚未发送');return}setPending(next);void send(next)}
 const save=()=>{if(!editor)return;begin('task-card-edit',{cardId:editor.cardId,expectedVersion:editor.expectedVersion,title:editor.title,body:editor.body,assigneeSessionId:editor.assigneeSessionId||undefined},'修改')}
 const publishable=cards.filter(c=>selected.includes(c.id)&&!publications.some(p=>p.cards.some(v=>v.cardId===c.id&&v.version===c.version)))
 const selectedCard=editor?cards.find(c=>c.id===editor.cardId):undefined
 const dirty=!!editor&&!!selectedCard&&(editor.title!==selectedCard.title||editor.body!==selectedCard.body||editor.assigneeSessionId!==(selectedCard.assigneeSessionId??''))
 const statusNames:Record<string,string>={queued:'等待原成员',delivering:'投递中',delivered:'已接收，等待卡片',offline:'原成员未连接',failed:'投递失败',uncertain:'送达待核实',cancelled:'等待已结束'}
 const retry=(d:DiscussionRecord,sid:string)=>begin('discussion-retry',{discussionId:d.id,sessionId:sid},'重试原生成请求')
 return <div style={{position:'absolute',inset:8,zIndex:2200,background:'var(--dsw-alias-bg-base)',border:'1px solid var(--dsw-alias-border-l2)',borderRadius:10,boxShadow:'0 10px 50px #0003',display:'flex',flexDirection:'column',overflow:'hidden'}} role="dialog" aria-modal="true" aria-label="任务卡生成与修改" tabIndex={-1} ref={dialog} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();onClose()}if(e.key==='Tab'){const nodes=[...(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]),textarea:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex="0"]')??[])].filter(x=>x.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}>
  <header style={{display:'flex',gap:8,alignItems:'center',padding:12,borderBottom:'1px solid var(--dsw-alias-border-l2)'}}><strong style={{flex:1}}>任务卡生成与修改</strong><button style={button} onClick={onClose}>关闭</button></header>
  <div style={{padding:12,overflow:'auto',minHeight:0,flex:1}}>
   {readOnly&&<p role="status">会议已归档，仅查看历史；修改、调整、重试与发布均暂停。</p>}<p>由你已@的原成员提出后续工作。生成者与执行者分别显示；生成和修改属于准备工作，确认发布后才通知执行。</p>
   {pending&&<div role="status">{pending.label}的原请求待核实，重开后仍保留。<button style={button} disabled={readOnly||busy} onClick={()=>void send(pending)}>核对并重试原请求</button></div>}
   {error&&<p role="alert" style={{color:'var(--dsw-alias-error-primary,#b42318)'}}>{error}</p>}{notice&&<p role="status">{notice}</p>}
   {generations.length===0&&<p>请在讨论输入区@原成员，点击「任务卡生成」。可以不填写额外正文。</p>}
   {generations.map(g=><section key={g.id} style={{borderBottom:'1px solid var(--dsw-alias-border-l2)',padding:'8px 0'}}><strong>{g.kind==='adjust'?'指定卡片调整':'后续工作生成'}</strong>{g.recipientIds.map(sid=>{const response=g.responses.find(x=>x.sessionId===sid),d=discussions.find(x=>x.id===g.discussionId),delivery=d?.deliveries.find(x=>x.toSessionId===sid);return <div key={sid}><button style={button} onClick={()=>{onClose();onOpenMember?.(sid)}}>{name(sid)}</button> · {response?response.emptyReason?`无待办：${response.emptyReason}`:`已返回${response.cardIds.length}张卡`:statusNames[delivery?.status??'queued']}{delivery?.error&&<span role="status"> · {delivery.error}</span>}{!response&&d&&['offline','failed','uncertain'].includes(delivery?.status??'')&&<button style={button} disabled={readOnly||busy||!!pending} onClick={()=>retry(d,sid)}>重试此成员原请求</button>}</div>})}</section>)}
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,280px),1fr))',gap:12,marginTop:12}}><section aria-label="逐项任务卡清单">{cards.map(c=>{const published=publications.find(p=>p.cards.some(v=>v.cardId===c.id&&v.version===c.version));return <article key={c.id} style={{padding:10,marginBottom:8,border:'1px solid var(--dsw-alias-border-l2)',borderRadius:8}}><label><input type="checkbox" aria-label={`选择${c.title}`} checked={selected.includes(c.id)} disabled={readOnly||!!published||busy||!!pending} onChange={e=>{setConfirm(false);setSelected(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}}/> {c.title} · v{c.version}</label><small style={{display:'block',marginTop:4}}>{batch(c)} · {new Date(c.createdAt).toLocaleString()}</small><p style={{margin:'6px 0'}}>生成：{name(c.generatorSessionId)} · 执行：{name(c.assigneeSessionId)}</p><button style={button} disabled={!readOnly&&(busy||!!pending)} onClick={()=>choose(c)}>查看全文与修改</button>{published&&<p>{published.status==='published'?'此版本已发布':'此版本已批准，写入待核实'}{published.cards.find(v=>v.cardId===c.id)?.relativePath&&` · ${published.cards.find(v=>v.cardId===c.id)!.relativePath}`}</p>}</article>})}{!cards.length&&generations.length>0&&<p>等待各位原成员返回卡片；其他成员失败不会重新生成成功项。</p>}</section>
   {editor&&<section aria-label="任务卡正文编辑"><label>名称<input style={input} value={editor.title} disabled={readOnly||busy||!!pending} onChange={e=>edit({...editor,title:e.target.value})}/></label><p>编辑基于 v{editor.expectedVersion}，服务器当前 v{selectedCard?.version??'未知'}。刷新不会替换正在编辑的正文。</p><label>完整Markdown正文<textarea style={{...input,minHeight:250,fontFamily:'inherit'}} value={editor.body} disabled={readOnly||busy||!!pending} onChange={e=>edit({...editor,body:e.target.value})}/></label><label>确认责任成员<select style={input} value={editor.assigneeSessionId} disabled={readOnly||busy||!!pending} onChange={e=>edit({...editor,assigneeSessionId:e.target.value})}><option value="">待确认</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button style={button} disabled={readOnly||busy||!!pending||!dirty||!editor.body.trim()||!editor.title.trim()} onClick={save}>保存本卡修改</button><details><summary>对照历史版本</summary>{selectedCard?.versions.map(v=><div key={v.version}><strong>v{v.version} · {v.source==='user'?'用户修改':v.source==='adjustment'?'采纳调整':'原成员生成'}</strong><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{v.body}</pre></div>)}</details><label>让原生成者调整本卡<textarea style={{...input,minHeight:60}} value={editor.note} disabled={readOnly||busy||!!pending} onChange={e=>edit({...editor,note:e.target.value})}/></label><button style={button} disabled={readOnly||busy||!!pending||dirty||!editor.note.trim()||!selectedCard} onClick={()=>begin('task-card-adjust',{cardId:editor.cardId,expectedVersion:editor.expectedVersion,note:editor.note},'本卡调整请求')}>交给原生成者调整这一卡</button>{dirty&&<p>先保存当前编辑，再请求调整或发布。</p>}{selectedCard?.proposals.filter(p=>!p.adoptedVersion).map(p=><details key={p.id}><summary>调整建议 · 基于 v{p.baseVersion}（不会覆盖当前正文）</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{p.body}</pre><button style={button} disabled={readOnly||busy||!!pending||dirty||p.baseVersion!==selectedCard.version} onClick={()=>begin('task-card-adopt',{cardId:selectedCard.id,proposalId:p.id,expectedVersion:selectedCard.version},'采纳调整建议')}>采纳此建议版本</button>{p.baseVersion!==selectedCard.version&&<p>你已修改为新版本，请对照建议手动合并，不直接覆盖。</p>}</details>)}</section>}</div>
   {publishable.length>0&&<section style={{paddingTop:12,borderTop:'1px solid var(--dsw-alias-border-l2)'}}>{!confirm?<button style={button} disabled={readOnly||busy||!!pending||dirty} onClick={()=>{setApproval(structuredClone(publishable));setConfirm(true)}}>核对选定的{publishable.length}张卡</button>:<div><p>仅发布以下版本，写入本会文件夹成功后通知所列责任成员执行。未选中的卡不会执行。</p>{approval.map(c=><p key={c.id}>{c.title} · v{c.version} · {batch(c)} · 执行：{name(c.assigneeSessionId)}</p>)}<button style={button} disabled={readOnly||busy||!!pending||dirty||approval.some(c=>!c.assigneeSessionId)} onClick={()=>begin('task-card-publish',{cards:approval.map(c=>({cardId:c.id,version:c.version})),execute:true},'选定卡片发布')}>确认发布并通知执行</button><button style={button} onClick={()=>setConfirm(false)}>返回修改</button>{publishable.some(c=>!c.assigneeSessionId)&&<p>请先为所选卡确认责任成员并保存。</p>}</div>}</section>}
  </div>
 </div>
}
