import {queuedWorkflowSlot} from '../workflow-slot.ts'
import {WorkflowSteps} from './WorkflowSteps.tsx'
import {makeStepsDefinition,isStepsDefinition,stepsUserNodes} from '../workflow-steps.ts'
import {TaskRecovery} from './TaskRecovery.tsx'
import {RevisionPanel} from './RevisionPanel.tsx'
import {effectiveReleaseTasks,reviewState,revisionChild} from '../task-review.ts'
import {useEffect,useRef,useState} from 'react'
import type {WorkflowDefinition,WorkflowNode,WorkflowEdge,WorkflowState,WorkflowNodeView,WorkflowPlan,GraphIssue,WorkflowCardBinding} from '../workflow-types.ts'
import type {MeetingMessage,MeetingAsset,ReleaseDraft} from '../meeting-flow-types.ts'
import {validateWorkflowGraph,validateWorkflowDraft,layoutWorkflow,workflowSemantic} from '../workflow-graph.ts'
import {WorkflowCanvas,workflowLabels} from './WorkflowCanvas.tsx'
import {clampWorkflowZoom} from './workflow-viewport.ts'
import {WorkflowToolbar,type WorkflowToolbarOption} from './WorkflowToolbar.tsx'
import {WorkflowInspector} from './WorkflowInspector.tsx'
import {STEP_POLICY,stepPolicyDraft} from './workflow-step-policy.ts'
import {workflowNeedsExplicitResume,workflowSchemaSupported} from '../workflow-types.ts'
import {PublishPanel} from './PublishPanel.tsx'
import {scopedLocal,localScopeId,meetingCall,readLocal,writeLocal,useLocalPersistence,uiButton as button,uiInput as input} from './ui-state.ts'
import {editWorkflowEdge,removeWorkflowEdge,removeWorkflowNode} from '../workflow-editor.ts'
import {workflowBudget} from '../workflow-budget.ts'

interface WorkflowMeeting {meetingId:string;workflow?:WorkflowState;workflowViews?:WorkflowNodeView[];messages?:MeetingMessage[];assets?:MeetingAsset[];releases?:ReleaseDraft[];releasePaused?:boolean;archivedAt?:number}
const id=()=>crypto.randomUUID()
const blank=():WorkflowDefinition=>makeStepsDefinition(id())
function template(members:{id:string;name:string}[]):WorkflowDefinition {
 const d={...blank(),steps:undefined},work=(nodeId:string,title:string,index:number):WorkflowNode=>({id:nodeId,title,kind:'work',memberIds:members[index]?[members[index]!.id]:[],instruction:'根据所选资料处理并正式提交结果',inputs:[],includeIncoming:true,requireReview:false,autoReceiveAndRun:false})
 d.entryId='proposal';d.title='方案评审与返工';d.nodes=[work('proposal','提出方案',0),work('tech','技术评审',1),work('budget','预算评审',2),{id:'gate',title:'汇合并决定',kind:'join',memberIds:[],instruction:'',inputs:[],includeIncoming:true,decision:true},work('revise','修改方案',0),{id:'minutes',title:'整理纪要',kind:'minutes',memberIds:[],instruction:'基于本轮结果整理决策、任务进展与未决事项',inputs:[],includeIncoming:true}]
 d.edges=[{id:'e1',from:'proposal',to:'tech',kind:'flow'},{id:'e2',from:'proposal',to:'budget',kind:'flow'},{id:'e3',from:'tech',to:'gate',kind:'flow'},{id:'e4',from:'budget',to:'gate',kind:'flow'},{id:'approve',from:'gate',to:'minutes',kind:'choice',label:'通过'},{id:'rework',from:'gate',to:'revise',kind:'choice',label:'需要修改'},{id:'back1',from:'revise',to:'tech',kind:'loop',loopId:'review'},{id:'back2',from:'revise',to:'budget',kind:'loop',loopId:'review'}]
 d.parallelGroups=[{id:'parallel',sourceId:'proposal',branchIds:['tech','budget'],joinId:'gate'}];d.loops=[{id:'review',nodeIds:['tech','budget','gate','revise'],entryIds:['tech','budget'],gateId:'gate',advanceId:'revise',maxRounds:3}]
 d.positions={proposal:{x:25,y:175},tech:{x:300,y:35},budget:{x:300,y:250},gate:{x:585,y:175},revise:{x:585,y:440},minutes:{x:875,y:175}};return d
}

export function WorkflowPanel({meeting,members,onChanged,onOpenSession,onNavigate}:{onNavigate?:(page:string)=>void;meeting:WorkflowMeeting;members:{id:string;name:string}[];onChanged:()=>Promise<void>;onOpenSession:(id:string)=>void}):React.ReactNode {
 const {readLocal,writeLocal,meetingCall:rawMeetingCall}=scopedLocal(useRef(localScopeId()).current)
 const {meetingId,workflow,messages=[],assets=[],releases=[]}=meeting
 const key=`workflow-editor.${meetingId}`
 const legacyActive=!!workflow&&workflowSchemaSupported(workflow.schemaVersion)&&workflow.runs.some(r=>r.status==='active'&&r.executionPolicy!==STEP_POLICY)
 const normalizeDraft=(definition:WorkflowDefinition)=>isStepsDefinition(definition)||legacyActive||workflow&&!workflowSchemaSupported(workflow.schemaVersion)?definition:stepPolicyDraft(definition)
 const [draft,setDraft]=useState(()=>{const saved=readLocal<{definition:WorkflowDefinition;baseRevision?:number}|undefined>(key,undefined)??{definition:workflow?.draft??blank(),baseRevision:workflow?.draft?.revision};return {...saved,definition:normalizeDraft(saved.definition)}})
 const [dirty,setDirty]=useState(()=>!!readLocal(key,undefined)||!!workflow?.draft&&!legacyActive&&workflow.draft.executionPolicy!==STEP_POLICY),[selected,setSelected]=useState(()=>readLocal(`workflow-selection.${meetingId}`,isStepsDefinition(draft.definition)?'':draft.definition.entryId)),[mode,setMode]=useState<'sequence'|'graph'>(()=>readLocal<unknown>(`workflow-view.${meetingId}`,'sequence')==='graph'?'graph':'sequence')
 const [zoom,setZoom]=useState(0.8),[issues,setIssues]=useState<GraphIssue[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [fitRequest,setFitRequest]=useState(0),[manualZoomRequest,setManualZoomRequest]=useState(0)
 const [preview,setPreviewRaw]=useState<{plan:WorkflowPlan;retry:boolean;requestId:string;initial?:boolean;collaboration?:'manual'|'automatic';perNode?:boolean}>(),[historyId,setHistoryId]=useState('')
 const [historyProjection,setHistoryProjection]=useState<{meetingId:string;runId:string;phase:'loading'|'ready'|'error';views:WorkflowNodeView[];error?:string}>(),[historyRetry,setHistoryRetry]=useState(0)
 const historyRequest=useRef(0),localPersistence=useLocalPersistence()
 const [confirm,setConfirmRaw]=useState<{text:string;action:()=>Promise<void>}>(),[supplement,setSupplement]=useState<{taskId:string;sessionId:string}>()
 const [collaboration,setCollaboration]=useState<'manual'|'automatic'>(()=>readLocal(`workflow-collaboration.${meetingId}`,'manual'))
 const [stage,setStage]=useState<{nodeId:string;text:string;messageIds:string[];assetIds:string[];requestId:string;sent?:boolean}|undefined>(()=>readLocal(`workflow-stage.${meetingId}`,undefined)),[publishedCards,setPublishedCards]=useState<{id:string;publicationId:string;version:number;title:string;body:string;assigneeSessionId?:string;releaseId?:string;messageIds:string[];assetIds:string[];fileRef:{fileId:string;sha256:string;relativePath:string}}[]>([])
 useEffect(()=>{writeLocal(`workflow-stage.${meetingId}`,stage)},[stage,meetingId])
 const [revisionTarget,setRevisionTarget]=useState<string>()
 const revisionTask=releases.flatMap(r=>r.tasks).find(t=>t.taskId===revisionTarget)
 const [bypass,setBypass]=useState<{nodeId:string;activationId?:string;reason:string}>()
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[edgeKind,setEdgeKind]=useState<'flow'|'choice'|'loop'>('flow'),[edgeLabel,setEdgeLabel]=useState(''),[edgeLoop,setEdgeLoop]=useState('')
 const [edgeDraft,setEdgeDraft]=useState<(WorkflowEdge&{existing?:boolean})>(),[extraWork,setExtraWork]=useState(30),[extraMinutes,setExtraMinutes]=useState(0)
 const [budgetRequest,setBudgetRequest]=useState<{runId:string;requestId:string;work:number;minutes:number;expected:{workAttempts:number;minutesStarts:number};confirmed:true}|undefined>(()=>readLocal(`workflow-budget-request.${meetingId}`,undefined))
 const busyRef=useRef(false),container=useRef<HTMLDivElement>(null),previewRef=useRef<HTMLDivElement>(null),readySectionRef=useRef<HTMLElement>(null),contentRef=useRef<HTMLDivElement>(null),edgeSettingsRef=useRef<HTMLElement>(null)
 const active=workflow&&workflowSchemaSupported(workflow.schemaVersion)?workflow.runs.find(r=>r.status==='active'):undefined,run=historyId?workflow?.runs.find(r=>r.id===historyId):active
 const historical=!!historyId&&historyId!==active?.id,missingHistory=historical&&!run,d=historical&&run?run.definition:draft.definition
 const matchingHistory=historyProjection?.meetingId===meetingId&&historyProjection?.runId===historyId?historyProjection:undefined
 const views=historical?(matchingHistory?.phase==='ready'?matchingHistory.views:[]):active?meeting.workflowViews??[]:[]
 const lastRun=workflow&&workflowSchemaSupported(workflow.schemaVersion)?workflow.runs.at(-1):undefined,nextDraft=!historyId&&!active&&!!lastRun
 const node=missingHistory||workflow&&!workflowSchemaSupported(workflow.schemaVersion)?undefined:d.nodes.find(n=>n.id===selected&&!n.stepsInternal),view=views.find(v=>v.nodeId===selected),activation=run?.activations.find(a=>a.id===view?.activationId),release=releases.find(r=>r.id===activation?.releaseId)
 const perNode=d.executionPolicy===STEP_POLICY,freeSteps=isStepsDefinition(d),sequenceMode=mode==='sequence',startIssues=freeSteps?validateWorkflowGraph(d):[]
 const frozen=!!active,readOnly=historical||!!meeting.archivedAt||!!workflow&&!workflowSchemaSupported(workflow.schemaVersion)
 const compatibleVersion=!workflow||workflowSchemaSupported(workflow.schemaVersion)?'supported':workflow.schemaVersion
 const mutationKey=JSON.stringify([meetingId,historyId,readOnly,compatibleVersion,d.id]),alive=useRef(true)
 const mutableView=useRef({key:mutationKey,epoch:0,readOnly})
 if(mutableView.current.key!==mutationKey)mutableView.current={key:mutationKey,epoch:mutableView.current.epoch+1,readOnly}
 const mutationOwner=mutableView.current,canMutate=()=>alive.current&&!mutableView.current.readOnly&&mutableView.current.key===mutationOwner.key&&mutableView.current.epoch===mutationOwner.epoch
 const setConfirm=(value:typeof confirm)=>{if(canMutate())setConfirmRaw(value)}
 const previewKey=readOnly?'readonly:'+historyId:JSON.stringify([d.id,d.revision,workflowSemantic(d),dirty])
 const previewEpoch=useRef({key:previewKey,version:0})
 if(previewEpoch.current.key!==previewKey)previewEpoch.current={key:previewKey,version:previewEpoch.current.version+1}
 const capturedPreviewEpoch=previewEpoch.current.version,previewCurrent=()=>canMutate()&&previewEpoch.current.version===capturedPreviewEpoch
 const setPreview=(value:typeof preview)=>{if(canMutate()&&(value===undefined||previewCurrent()))setPreviewRaw(value)}
 useEffect(()=>{setPreviewRaw(undefined)},[previewKey])
 const meetingCall=(mid:string,actionName:string,body:unknown={})=>{
  if(actionName!=='workflow-view'&&!canMutate())return Promise.reject(Error('当前查看对象已变化或只读，未执行流程操作'))
  return rawMeetingCall(mid,actionName,body).then(value=>{if(actionName!=='workflow-view'&&!canMutate())throw Error('当前查看对象已变化，保留已接受的服务端操作；未继续本地修改');return value})
 }
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 useEffect(()=>{if(readOnly){setPreviewRaw(undefined);setConfirmRaw(undefined);setBypass(undefined);setRevisionTarget(undefined);setSupplement(undefined);setEdgeDraft(undefined)}},[readOnly])
 const changeHistory=(value:string)=>{
  const nextReadOnly=!!value&&value!==active?.id||!!meeting.archivedAt||!!workflow&&!workflowSchemaSupported(workflow.schemaVersion)
  mutableView.current={key:JSON.stringify([meetingId,value,nextReadOnly,compatibleVersion,value?workflow?.runs.find(r=>r.id===value)?.definition.id??d.id:draft.definition.id]),epoch:mutableView.current.epoch+1,readOnly:nextReadOnly}
  setHistoryId(value);setPreviewRaw(undefined);setConfirmRaw(undefined);setBypass(undefined);setRevisionTarget(undefined);setSupplement(undefined);setEdgeDraft(undefined);setError('');setNotice('')
 }
 const inspectorKey=JSON.stringify([meetingId,d.id,selected,mode,d.executionPolicy,readOnly,active?.id,!!active?.activations.some(a=>a.nodeId===selected&&!a.temporary)]),inspectorIdentity=useRef({key:inspectorKey,epoch:0})
 if(inspectorIdentity.current.key!==inspectorKey)inspectorIdentity.current={key:inspectorKey,epoch:inspectorIdentity.current.epoch+1}
 const inspectorOwner=inspectorIdentity.current,validInspector=()=>canMutate()&&inspectorIdentity.current.key===inspectorOwner.key&&inspectorIdentity.current.epoch===inspectorOwner.epoch
 const budget=run?workflowBudget(run):undefined,admissionBlocked=!!run?.paused&&(!run.automatic||run.automatic.pauseReason==='主持人暂停后续执行'||workflowNeedsExplicitResume(run))
 const edgeLocked=readOnly||!!(edgeDraft&&active?.activations.some(a=>!a.temporary&&(a.nodeId===edgeDraft.from||a.nodeId===edgeDraft.to)))
 const name=(memberId:string)=>members.find(m=>m.id===memberId)?.name??memberId
 useEffect(()=>{if(dirty)writeLocal(key,draft)},[draft,dirty,key])
 useEffect(()=>{writeLocal(`workflow-budget-request.${meetingId}`,budgetRequest)},[budgetRequest,meetingId])
 useEffect(()=>{if(!dirty&&workflow?.draft)setDraft({definition:normalizeDraft(workflow.draft),baseRevision:workflow.draft.revision})},[workflow?.draft?.revision,workflow?.draft?.layoutRevision,dirty])
 useEffect(()=>{writeLocal(`workflow-selection.${meetingId}`,selected);writeLocal(`workflow-view.${meetingId}`,mode)},[selected,mode,meetingId])
 useEffect(()=>{
  const request=++historyRequest.current
  if(!historyId||!historical){setHistoryProjection(undefined);return}
  let alive=true
  setHistoryProjection({meetingId,runId:historyId,phase:'loading',views:[]})
  void meetingCall(meetingId,'workflow-view',{runId:historyId}).then(v=>{if(alive&&request===historyRequest.current)setHistoryProjection({meetingId,runId:historyId,phase:'ready',views:v.views})}).catch(e=>{if(alive&&request===historyRequest.current)setHistoryProjection({meetingId,runId:historyId,phase:'error',views:[],error:e instanceof Error?e.message:String(e)})})
  return()=>{alive=false}
 },[historyId,meetingId,historical,historyRetry])
 useEffect(()=>{if(preview)previewRef.current?.scrollIntoView({block:'nearest'})},[preview])
 useEffect(()=>{if(edgeDraft)edgeSettingsRef.current?.scrollIntoView({block:'nearest'})},[edgeDraft?.id])
 const action=async(fn:()=>Promise<void>)=>{if(!canMutate()||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(canMutate())setError(e instanceof Error?e.message:String(e))}finally{busyRef.current=false;if(alive.current)setBusy(false)}}
 const call=async(actionName:string,body:object)=>{if(!canMutate())return;await meetingCall(meetingId,actionName,body);if(canMutate())await onChanged()}
 const edit=(next:WorkflowDefinition,layoutOnly=false)=>{if(!canMutate())return;previewEpoch.current.version++;setConfirmRaw(undefined);setDraft(x=>({...x,definition:normalizeDraft(next)}));setDirty(true);setIssues([]);if(!layoutOnly)setPreview(undefined)}
 const applyEdge=(edge:WorkflowEdge,existing?:string)=>{if(!canMutate())return;try{setError('');edit(editWorkflowEdge(d,edge,existing,active));setEdgeDraft(undefined);setNotice('连线已修改，保存后生效；没有启动任务。')}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const selectEdge=(edgeId:string)=>{const e=d.edges.find(e=>e.id===edgeId);if(e)setEdgeDraft({...e,existing:true})}
 const connect=(from:string,to:string)=>{if(!canMutate())return;const loop=d.loops.find(l=>l.advanceId===from&&l.nodeIds.includes(to)),choice=d.nodes.find(n=>n.id===from)?.decision;setEdgeDraft({id:id(),from,to,kind:loop?'loop':choice?'choice':'flow',...(loop?{loopId:loop.id}:{}),...(choice?{label:''}:{})});setError('')}
 const deleteEdge=(edgeId:string)=>{if(!canMutate())return;try{edit(removeWorkflowEdge(d,edgeId,active));setEdgeDraft(undefined);setNotice('连线已移除；请保存流程。')}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const save=(confirmedFuture=false)=>action(async()=>{
  if(active?.automatic&&dirty&&JSON.stringify(workflowSemantic(d))!==JSON.stringify(workflowSemantic(active.definition))&&!confirmedFuture){setConfirm({text:'确认更新自动协作尚未开始的环节、要求和资料？后续自动接力将使用这次配置；历史激活的节点与输入保持冻结。',action:async()=>{const result=await meetingCall(meetingId,'workflow-save',{definition:d,expectedRevision:draft.baseRevision,confirmedFuture:true});setDraft({definition:result.definition,baseRevision:result.definition.revision});setDirty(false);writeLocal(key,undefined);await onChanged();setNotice(active?.executionPolicy===STEP_POLICY?'未来环节规则已保存，本轮暂停；核对后确认继续，保存本身没有开始任务。':'尚未开始的环节已更新；历史输入没有变化。')}});return}
  const errors=validateWorkflowDraft(d);setIssues(errors);if(errors.length){setNotice('请先处理配置问题，尚未保存。');return}
  const result=await meetingCall(meetingId,'workflow-save',{definition:d,expectedRevision:draft.baseRevision,confirmedFuture})
  setDraft({definition:result.definition,baseRevision:result.definition.revision});setDirty(false);writeLocal(key,undefined);await onChanged();setNotice('流程已保存；没有投递消息。')
 })
 const inspect=(ids:string[],retry=false)=>action(async()=>{
  if(!run||dirty||!previewCurrent())return;const value=await meetingCall(meetingId,'workflow-preview',{runId:run.id,nodeIds:ids,retry});setPreview({plan:value.plan,retry,requestId:id()})
 })
 const start=()=>action(async()=>{if(!preview||dirty||!previewCurrent())return;if(preview.initial)await call('workflow-initial-start',{definitionRevision:preview.plan.definitionRevision,fingerprint:preview.plan.fingerprint,requestId:preview.requestId,mode:preview.collaboration??'manual',confirmed:true});else if(run)await call('workflow-start',{runId:run.id,nodeIds:preview.plan.nodeIds,fingerprint:preview.plan.fingerprint,requestId:preview.requestId,retry:preview.retry,confirmed:true});else return;setPreview(undefined);setNotice(preview.perNode||run?.executionPolicy===STEP_POLICY?'已确认本轮逐环节规则；只有勾选环节可自动接力，未勾选的仍需手动开始。':preview.collaboration==='automatic'||run?.automatic?'已确认自动协作；例行环节按冻结配置接力，验收、选路、输入不足或异常处等待你处理。':'已授权。输入将投递到原窗口；下一环节仍等你开始。')})
 const nodeOptions=(value:string,set:(v:string)=>void,label:string)=><select aria-label={label} style={input} value={value} onChange={e=>set(e.target.value)}><option value="">请选择环节</option>{d.nodes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select>
 const ready=views.filter(v=>v.status==='ready'&&(run?.executionPolicy!==STEP_POLICY||d.nodes.find(n=>n.id===v.nodeId)?.autoReceiveAndRun!==true||d.nodes.find(n=>n.id===v.nodeId)?.confirmation===true))
 const automaticSummary='普通投递最多'+d.limits.workAttempts+'次'+(freeSteps?'':'，秘书最多'+d.limits.minutesStarts+'次')+'；'+(freeSteps?stepsUserNodes(d):d.nodes).map(n=>n.title+(perNode?(n.autoReceiveAndRun?'（自动接收并运行）':'（手动开始）'):'')+'→'+(n.kind==='minutes'?'秘书':n.kind==='join'?'汇合／选路':n.memberIds.map(name).join('、'))+(n.requireReview?'（成果需验收）':'')+(n.confirmation?'（开始需确认）':'')).join('；')+(d.loops.length?'；自动返工上限：'+d.loops.map(l=>(d.nodes.find(n=>n.id===l.gateId)?.title??'返工')+l.maxRounds+'轮').join('、'):'')
 const historyOptions:WorkflowToolbarOption[]=[
  {value:'',label:nextDraft?'下一轮编辑草稿':active?`本轮流程 · ${active.paused?'已暂停':active.automatic?'自动接力':'手动主持'}`:'当前配置'},
  ...(workflow?.runs??[]).map((r,i)=>({value:r.id,label:`第${i+1}次运行 · ${r.status==='active'?'进行中':r.status==='completed'?'已完成':'已停止'}`})),
  ...(missingHistory?[{value:historyId,label:'所选历史运行不可用'}]:[]),
 ]
 const stepControl=(n:WorkflowNode)=><label className="rt-step-auto"><input type="checkbox" aria-label={"自动接收上游信息并运行 "+n.title} checked={n.autoReceiveAndRun===true} disabled={readOnly||busy||legacyActive||!!active?.activations.some(a=>a.nodeId===n.id&&!a.temporary)} onChange={e=>{if(!validInspector()||legacyActive||active?.activations.some(a=>a.nodeId===n.id&&!a.temporary))return;edit({...d,nodes:d.nodes.map(old=>old.id===n.id?{...old,autoReceiveAndRun:e.target.checked,...(e.target.checked?{includeIncoming:true}:{})}:old)})}}/>自动接收上游信息并运行</label>
 const runStatus=missingHistory?'历史记录不可用':historical?'历史运行记录':meeting.archivedAt?'会议已归档 · 只读':workflow&&!workflowSchemaSupported(workflow.schemaVersion)?'当前版本无法解释此流程':run?run.paused?'本轮已暂停':run.executionPolicy===STEP_POLICY?'按环节规则运行中':run.automatic?'自动协作中':'手动主持中':nextDraft?'下一轮尚未启动':'本轮尚未启动'
 const runNote=historical?'仅查看本次记录，不执行或修改。':readOnly?'当前内容只读，修改与执行入口已收起。':run?.paused?run.automatic?<span>暂停原因：{run.automatic.pauseReason??'本轮已暂停'}。检查后按本轮冻结配置继续{dirty?'；未保存修改不会用于执行':''}。</span>:<span>继续已确认的工作，新环节仍需手动开始。{dirty?'按已确认配置继续；未保存修改不会用于执行。':''}</span>:run?.executionPolicy===STEP_POLICY?'勾选环节按规则接力；未勾选环节等待手动预览开始，验收、选路与异常仍停下。':run?.automatic?'按本轮规则推进；验收、选路与异常等待你处理。':run?ready.length?'新环节先预览，再由你确认开始。':'等待当前结果或处理本轮事项。':dirty||!workflow?.draft?'先保存配置，保存后可预览；保存不会发任务。':freeSteps&&startIssues.length?'已保存为草稿；请补齐环节名称和成员Agent，再保存并预览。':collaboration==='automatic'?'先预览完整配置并确认，再按规则自动接力。':'先预览，再确认启动本轮；普通讨论不受影响。'
 const primaryAction=!readOnly? !active?<button style={button} data-workflow-primary="" disabled={busy||dirty||!workflow?.draft||meeting.releasePaused||startIssues.length>0} onClick={()=>{if(dirty||!workflow?.draft||meeting.releasePaused||startIssues.length||!previewCurrent())return;void action(async()=>{const requestId=id();if(!perNode&&d.nodes.find(n=>n.id===d.entryId)?.kind==='join'){if(collaboration==='automatic'){setConfirm({text:'确认按当前保存配置开启自动协作？'+automaticSummary+'。成员、资料和额度按本次快照使用，验收与选路等待主持，重启后不会自动续跑。',action:()=>call('workflow-create',{definitionRevision:workflow!.draft!.revision,requestId,mode:collaboration,confirmed:true})});return}await call('workflow-create',{definitionRevision:workflow!.draft!.revision,requestId});setNotice('运行已建立，请在入口汇合节点选择路线。')}else{const value=await meetingCall(meetingId,'workflow-initial-preview',{requestId});setPreview({plan:value.plan,retry:false,requestId,initial:true,collaboration:perNode?'automatic':collaboration,perNode})}})}}>{!perNode&&d.nodes.find(n=>n.id===d.entryId)?.kind==='join'?'建立本轮并主持选路…':'预览并启动本轮…'}</button>:run?.paused?<button style={button} data-workflow-primary="" disabled={busy} onClick={()=>{if(run.paused&&run.automatic)setConfirm({text:`${run.automatic.pauseReason??'流程已暂停'}。确认已检查输入、结果与原窗口，继续按本次冻结配置自动接力？不会重发已建档的执行。`,action:()=>call('workflow-control',{runId:run.id,control:'resume',confirmed:true})});else void action(()=>call('workflow-control',{runId:run.id,control:run.paused?'resume':'pause'}))}}>{run.paused?(run.automatic?'检查并继续自动协作…':'继续本轮'):'暂停后续执行'}</button>:run?.automatic&&run.executionPolicy!==STEP_POLICY?<button type="button" style={button} onClick={()=>contentRef.current?.scrollIntoView({block:'nearest'})}>查看当前进展</button>:ready.length===1?<button type="button" style={button} data-workflow-primary="" disabled={busy||dirty||admissionBlocked||meeting.releasePaused} onClick={()=>{if(!canMutate())return;setSelected(ready[0]!.nodeId);void inspect([ready[0]!.nodeId])}}>预览下一环节</button>:ready.length>1?<button type="button" style={button} onClick={()=>readySectionRef.current?.scrollIntoView({block:'nearest'})}>查看可开始环节</button>:<button type="button" style={button} onClick={()=>contentRef.current?.scrollIntoView({block:'nearest'})}>查看当前进展</button>:undefined

 const editSteps=(update:(current:WorkflowDefinition)=>WorkflowDefinition)=>{
  if(!canMutate()||busyRef.current)return
  previewEpoch.current.version++;setPreviewRaw(undefined);setConfirmRaw(undefined);setIssues([])
  setDraft(current=>current.definition.id===d.id?{...current,definition:update(current.definition)}:current);setDirty(true)
 }
 const prepareEmpty=()=>{
  if(!canMutate()||busyRef.current||active)return
  const next=makeStepsDefinition(id(),'会议进程',d.limits)
  mutableView.current={...mutableView.current,epoch:mutableView.current.epoch+1}
  setDraft({definition:next,baseRevision:workflow?.draft?.revision});setDirty(true);setSelected('');setMode('sequence');setPreviewRaw(undefined);setConfirmRaw(undefined);setIssues([]);setEdgeDraft(undefined);setNotice('已建立空白步骤草稿。旧配置和运行历史会保留，保存前尚未替换会议配置。')
 }
 const execution=node?<section aria-label="本环节执行" style={{border:'1px solid var(--dsw-alias-border-l2)',padding:12,borderRadius:12}}>{!freeSteps&&<b>{node.title} · {workflowLabels[view?.status??'not_started']}</b>}{view?.missing.map(x=><p key={x}>{x}</p>)}
    {!readOnly&&run&&node.kind!=='join'&&<button style={button} disabled={busy||!!stage?.sent} onClick={()=>setStage({nodeId:node.id,text:'',messageIds:[],assetIds:[],requestId:id()})}>添加环节资料／补充输入</button>}
    {stage&&stage.nodeId===node.id&&!readOnly&&run&&<section aria-label="补充环节输入"><p>目标：{node.title} · 沿用{node.kind==='minutes'?'会议秘书':node.memberIds.map(name).join('、')}。仅暂存到可用本轮或下一轮，确认不会立即投递，也不改变执行成员。</p><textarea aria-label="环节补充说明" disabled={busy||stage.sent} style={{...input,width:'100%',minHeight:75}} value={stage.text} onChange={e=>setStage({...stage,text:e.target.value})}/><details><summary>引用会议消息与资料</summary>{messages.filter(m=>!m.previewOnly).map(m=><label key={m.id} style={{display:'block'}}><input type="checkbox" disabled={busy||stage.sent} checked={stage.messageIds.includes(m.id)} onChange={()=>setStage({...stage,messageIds:stage.messageIds.includes(m.id)?stage.messageIds.filter(x=>x!==m.id):[...stage.messageIds,m.id]})}/>{m.text.slice(0,100)}</label>)}{assets.map(a=><label key={a.id} style={{display:'block'}}><input type="checkbox" checked={stage.assetIds.includes(a.id)} onChange={()=>setStage({...stage,assetIds:stage.assetIds.includes(a.id)?stage.assetIds.filter(x=>x!==a.id):[...stage.assetIds,a.id]})}/>{a.name} · v{a.version}</label>)}</details><div className="rt-workflow-tools"><button style={button} disabled={busy||!stage.text.trim()&&!stage.messageIds.length&&!stage.assetIds.length} onClick={()=>{const pending=stage;void action(async()=>{setStage({...pending,sent:true});const result=await meetingCall(meetingId,'workflow-input-add',{runId:run.id,nodeId:pending.nodeId,requestId:pending.requestId,text:pending.text,messageIds:pending.messageIds,assetIds:pending.assetIds,confirmed:true});setStage(current=>current?.requestId===pending.requestId?undefined:current);await onChanged();setNotice('资料已暂存到第'+(result.round||1)+'轮；没有立即执行。')})}}>确认暂存资料</button><button style={button} disabled={busy} onClick={()=>{if(stage.sent)setConfirm({text:'这次资料暂存的响应尚未确认，原请求可能已保存。确认关闭编辑，不重新提交或删除原资料？',action:async()=>{setStage(undefined)}});else setStage(undefined)}}>取消</button></div></section>}
    {!readOnly&&!active?.activations.some(a=>a.nodeId===node.id&&!a.temporary)&&<section aria-label="环节协作配置">{!freeSteps&&<label><input type="checkbox" checked={!!node.confirmation} onChange={e=>edit({...d,nodes:d.nodes.map(n=>n.id===node.id?{...n,confirmation:e.target.checked}:n)})}/>自动协作开始此环节前等待主持确认</label>}{node.kind==='work'&&<>{mode==='graph'&&!freeSteps&&<label style={{display:'block'}}><input type="checkbox" checked={!!node.requireReview} onChange={e=>edit({...d,nodes:d.nodes.map(n=>n.id===node.id?{...n,requireReview:e.target.checked}:n)})}/>正式成果需主持验收后才供下一环节使用</label>}<details><summary>绑定已发布任务卡</summary><button style={button} disabled={busy} onClick={()=>{void action(async()=>{const value=await meetingCall(meetingId,'workflow-published-cards',{});setPublishedCards(value.cards??[])})}}>查看已发布卡片</button>{publishedCards.map(c=><article key={c.publicationId+':'+c.id+':'+c.version}><strong>{c.title} · v{c.version}</strong><p style={{whiteSpace:'pre-wrap'}}>{c.body}</p><p>建议负责人：{c.assigneeSessionId?name(c.assigneeSessionId):'尚未指定'} · {c.assetIds.length}项材料 · {c.fileRef.relativePath}</p>{c.releaseId&&<p>这张卡已独立派发；绑定流程后，明确开始新的运行会再次作为新的环节执行，原任务记录保留。</p>}<button style={button} disabled={busy} onClick={()=>{void action(async()=>{const binding:WorkflowCardBinding={publicationId:c.publicationId,cardId:c.id,version:c.version,fileId:c.fileRef.fileId,sha256:c.fileRef.sha256},value=await meetingCall(meetingId,'workflow-bind-card',{node,binding});if(!validInspector())return;edit({...d,nodes:d.nodes.map(n=>n.id===node.id?value.node:n)});setNotice('已在流程草稿绑定这张已发布卡的要求、建议成员与材料版本；保存后生效，尚未执行。')})}}>使用此发布版本</button></article>)}{node.cardBinding&&<><p>已绑定任务卡v{node.cardBinding.version}。修改要求或固定资料前请解除绑定；历史执行不会改变。</p><button style={button} onClick={()=>{const {cardBinding,...next}=node;edit({...d,nodes:d.nodes.map(n=>n.id===node.id?next:n)})}}>解除卡片绑定，保留当前要求</button></>}</details></>}</section>}
    {!readOnly&&run&&node.decision&&view?.status==='waiting_decision'&&<div className="rt-workflow-tools">{d.edges.filter(e=>e.from===node.id&&e.kind==='choice').map(e=><button key={e.id} style={button} disabled={busy||dirty||run.paused&&!run.automatic?.pauseReason} onClick={()=>{void action(()=>call('workflow-choice',{runId:run.id,nodeId:node.id,edgeId:e.id}))}}>{e.label} → {d.nodes.find(n=>n.id===e.to)?.title}</button>)}</div>}
    {!readOnly&&run&&activation?.choiceEdgeId&&<button style={button} disabled={busy||run.paused} onClick={()=>{void action(()=>call('workflow-clear-choice',{runId:run.id,nodeId:node!.id,activationId:activation.id}))}}>撤销尚未执行的选择</button>}
    {!readOnly&&run&&node.kind==='join'&&view?.status==='waiting_inputs'&&d.parallelGroups.some(g=>g.joinId===node.id)&&<button style={button} disabled={busy||dirty||run.paused} onClick={()=>{void action(async()=>{const {plan}=await meetingCall(meetingId,'workflow-partial-preview',{runId:run.id,joinId:node.id});setConfirm({text:`使用已有结果继续，将跳过：${plan.branches.filter((b:{branchId:string})=>plan.skipBranchIds.includes(b.branchId)).map((b:{title:string})=>b.title).join('、')}。晚到结果不进入本次汇合，原窗口继续工作。`,action:()=>call('workflow-partial',{runId:run.id,joinId:node.id,skipBranchIds:plan.skipBranchIds,fingerprint:plan.fingerprint,confirmed:true,reason:'主持人在流程面板确认使用已有结果继续'})})})}}>使用已有结果继续…</button>}
    {activation?.minutesError&&<p role="alert">{activation.minutesError}</p>}{activation?.minutesId&&<p>纪要已生成，保存在“纪要”页；尚未发送的内容由你决定是否发送。</p>}
    {!readOnly&&run&&node.kind!=='join'&&!run.definition.loops.some(l=>l.advanceId===node.id)&&!['skipped','not_walked','waiting_inputs','limit'].includes(view?.status??'waiting_inputs')&&<button style={button} disabled={busy||dirty||run.paused} onClick={()=>setBypass({nodeId:node.id,activationId:view?.activationId,reason:''})}>跳过处理并沿用输入…</button>}
    {(release?effectiveReleaseTasks({releases},release):[]).map(t=><article key={t.taskId} style={{paddingTop:10,marginTop:10,borderTop:'1px solid var(--dsw-alias-border-l2)'}}><strong>{name(t.toSessionId)} · {t.status==='completed'?'已提交':t.status==='delivered'?'已投递，等待结果':workflowLabels[t.status]??t.status}</strong><TaskRecovery task={t}/>{t.error&&<p>{t.error}</p>}{t.result&&<details><summary>{t.result.slice(0,90)}{t.result.length>90?'…':''}</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{t.result}</p></details>}<div className="rt-workflow-tools" style={{marginTop:8}}><button style={button} onClick={()=>onOpenSession(t.toSessionId)}>打开原窗口</button>{!readOnly&&<>
     {['offline','uncertain'].includes(t.status)&&<button style={button} disabled={busy||run?.paused} onClick={()=>setConfirm({text:t.status==='uncertain'?'原消息可能已送达。检查原窗口后确认重试，可能重复执行并消耗额度。':'在原窗口恢复连接后重试投递。',action:()=>call('retry-release',{taskId:t.taskId,allowDuplicate:t.status==='uncertain'})})}>重试投递…</button>}
     {t.attempts>0&&['delivered','in_progress','uncertain','failed'].includes(t.status)&&<button style={button} onClick={()=>setSupplement({taskId:t.taskId,sessionId:t.toSessionId})}>人工补交</button>}
     {!['completed','cancelled'].includes(t.status)&&<button style={button} onClick={()=>setConfirm({text:'结束本项会议等待，不取消原窗口当前工作。',action:()=>call('close-task',{taskId:t.taskId,confirmed:true})})}>结束等待…</button>}
     {t.status==='completed'&&<><button style={button} disabled={busy||t.review==='accepted'} onClick={()=>{void action(()=>call('review-task',{taskId:t.taskId,review:'accepted'}))}}>验收通过</button><button style={button} disabled={busy||!!revisionChild({releases},t)} onClick={()=>{void action(async()=>{await call('review-task',{taskId:t.taskId,review:'changes_requested',note:t.reviewNote??''});setRevisionTarget(t.taskId)})}}>要求修改</button><span>{reviewState({releases},t)}</span></>}
    </>}</div><small>投递尝试{t.attempts}次 · {new Date(t.updatedAt).toLocaleString()}</small></article>)}
    {!readOnly&&run&&['submitted','failed','ended','waiting_review','changes_requested'].includes(view?.status??'')&&node.kind!=='join'&&<button style={{...button,marginTop:10}} disabled={busy||dirty||run.paused} onClick={()=>{void inspect([node.id],true)}}>预览重新执行…</button>}
    {!readOnly&&supplement&&<PublishPanel key={supplement.taskId} meetingId={meetingId} members={members} releases={releases} initialTarget={supplement} onChanged={onChanged}/>}
   </section>:undefined
 return <section ref={container} data-workflow-panel="" style={{fontSize:13,minWidth:0,overflowWrap:'anywhere',display:'flex',flexDirection:'column',flexShrink:0,gap:8,containerType:'inline-size',containerName:'rt-workflow'}}>
  <style>{`.rt-step-auto{display:flex;align-items:flex-start;gap:6px;margin:7px 4px;line-height:1.5;font-size:12px;overflow-wrap:anywhere}.rt-step-auto input{flex:none;margin-top:3px}.rt-workflow-layout{display:grid;grid-template-columns:minmax(0,1fr);gap:12}.rt-workflow-tools{display:flex;flex-wrap:wrap;gap:6}.rt-workflow-layout input,.rt-workflow-layout select{max-width:100%}.rt-workflow-content-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0}.rt-workflow-content-heading>button{padding:4px 9px}.rt-workflow-field{display:flex;flex-direction:column;gap:7px;min-width:0}@container rt-workflow (min-width:760px){.rt-workflow-layout:not(.rt-workflow-list-layout){grid-template-columns:minmax(0,1fr) 290px}}`}</style>
  <header><h3 style={{margin:0,fontSize:16}}>会议进程</h3><p style={{margin:'2px 0 0',color:'var(--dsw-alias-label-secondary)'}}>自行命名环节、指定成员，安排顺序与并行协作。</p></header>
  {nextDraft&&<p role="status">{lastRun!.status==='completed'?'上一轮已完成':'上一轮已停止'}。当前显示下一轮编辑草稿，尚未建立新运行；上一轮结果可在“正在查看”中选择。</p>}
  {!localPersistence.available&&<p role="alert">流程草稿仅在本次窗口保留，关闭后可能丢失：{localPersistence.reason}。可用“保存配置／保存修改”将有效安排保存到会议。</p>}
  {historical&&!missingHistory&&matchingHistory?.phase!=='ready'&&(matchingHistory?.phase==='error'?<p role="alert">读取历史运行失败：{matchingHistory.error} <button style={button} onClick={()=>setHistoryRetry(x=>x+1)}>重试读取此运行</button></p>:<p role="status">正在读取历史运行…</p>)}

  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{run&&run.executionPolicy!==STEP_POLICY&&mode==='sequence'&&<p role="status">{historical?'历史运行使用当时的'+(run.automatic?'全局自动接力':'手动主持')+'规则；当时没有此逐环节开关，未勾选不代表改写旧记录。':'旧运行仍按当时的规则执行；结束后在下一轮配置勾选自动环节。'}</p>}
  {workflow&&!workflowSchemaSupported(workflow.schemaVersion)&&<p role="alert">此会议流程来自更高版本，当前只读，请升级插件。</p>}
  <WorkflowToolbar
   view={mode} onViewChange={setMode} historyValue={historyId} historyOptions={historyOptions} onHistoryChange={changeHistory}
   historical={historical} readOnly={readOnly} viewingNote={historical&&run?`第${(workflow?.runs.findIndex(r=>r.id===run.id)??0)+1}次运行 · ${run.status==='completed'?'已完成':run.status==='active'?'进行中':'已停止'}`:meeting.archivedAt?'会议已归档':workflow&&!workflowSchemaSupported(workflow.schemaVersion)?'需要兼容版本才能查看':undefined}
   configurationStatus={dirty?'有未保存修改':workflow?.draft?`已保存 · v${workflow.draft.revision}`:'尚未保存'}
   configurationTone={dirty?'dirty':workflow?.draft?'saved':'unavailable'}
   configurationActions={!readOnly?<><button style={button} disabled={busy||!dirty} onClick={()=>{void save()}}>{workflow?.draft?'保存修改':'保存配置'}</button><button style={button} disabled={busy||!dirty} onClick={()=>{setConfirm({text:'放弃本地未保存的配置和布局修改，恢复最后保存版本？',action:async()=>{setDraft({definition:workflow?.draft??blank(),baseRevision:workflow?.draft?.revision});setDirty(false);writeLocal(key,undefined);setIssues([])}})}}>放弃修改</button></>:undefined}
   runStatus={runStatus} runNote={runNote}
   collaborationControls={!readOnly&&!active&&!perNode?<label>协作方式 <select aria-label="协作方式" style={input} value={collaboration} onChange={e=>{if(!canMutate())return;const next=e.target.value==='automatic'?'automatic':'manual';setCollaboration(next);writeLocal(`workflow-collaboration.${meetingId}`,next);setPreview(undefined)}}><option value="manual">手动主持</option><option value="automatic">按规则自动接力</option></select></label>:undefined}
   primaryAction={primaryAction}
   runOperations={!readOnly&&run?<>{!run.paused&&<button style={button} disabled={busy} onClick={()=>{if(run.paused&&run.automatic)setConfirm({text:`${run.automatic.pauseReason??'流程已暂停'}。确认已检查输入、结果与原窗口，继续按本次冻结配置自动接力？不会重发已建档的执行。`,action:()=>call('workflow-control',{runId:run.id,control:'resume',confirmed:true})});else void action(()=>call('workflow-control',{runId:run.id,control:run.paused?'resume':'pause'}))}}>暂停后续执行</button>}<button style={button} disabled={busy} onClick={()=>setConfirm({text:'停止本次流程的等待与未送出任务。普通成员原窗口继续工作。',action:()=>call('workflow-control',{runId:run.id,control:'stop',confirmed:true})})}>停止本轮…</button><button style={button} disabled={busy} onClick={()=>setConfirm({text:'确认所选路径已提交，结束本次运行并保留历史？仍有待处理任务时服务端会拒绝完成。',action:()=>call('workflow-control',{runId:run.id,control:'complete'})})}>完成本轮…</button></>:undefined}
   readOnlyReturn={historical?<button style={button} onClick={()=>changeHistory('')}>返回当前配置</button>:undefined}
   runtimeDetails={run?<details data-workflow-runtime-records=""><summary>执行次数与记录</summary><div style={{display:'flex',flexDirection:'column',gap:6,paddingTop:6}}>
    <p style={{margin:0}}>普通投递 {run.workReserved}/{budget!.workAttempts} · 秘书 {run.minutesStarted}/{budget!.minutesStarts}</p>
    <p style={{margin:0}}>限制会议触发次数；原窗口执行可能包含多次模型和工具调用。</p>
   {run.definition.loops.map(l=><p key={l.id} style={{margin:'6px 0 0'}}>返工：{d.nodes.find(n=>n.id===l.gateId)?.title} · 第{run.rounds[l.id]??1}轮 · {run.automatic?`自动最多${run.automatic.roundCaps[l.id]}轮`:'每轮由你开始，无轮次上限'}{run.automatic&&!readOnly&&<button style={button} disabled={busy} onClick={()=>setConfirm({text:`将自动轮次上限由${run.automatic!.roundCaps[l.id]}轮追加为${run.automatic!.roundCaps[l.id]!+1}轮？追加不启动；仍需检查并继续。`,action:()=>call('workflow-auto-rounds',{runId:run.id,loopId:l.id,expected:run.automatic!.roundCaps[l.id],maxRounds:run.automatic!.roundCaps[l.id]!+1,confirmed:true})})}>追加一轮…</button>}</p>)}
   {!readOnly&&<details><summary title="额度用完后不会自动增加。你可以追加次数；追加后仍需预览并开始环节。">手动追加执行额度</summary><div className="rt-workflow-tools" style={{marginTop:8}}><label>普通投递<input aria-label="追加普通投递" type="number" min={0} max={1000} value={extraWork} disabled={!!budgetRequest} style={{...input,width:100}} onChange={e=>setExtraWork(Number(e.target.value))}/></label><label>秘书生成<input aria-label="追加秘书生成" type="number" min={0} max={100} value={extraMinutes} disabled={!!budgetRequest} style={{...input,width:100}} onChange={e=>setExtraMinutes(Number(e.target.value))}/></label><button style={button} disabled={busy||!!budgetRequest||!Number.isInteger(extraWork)||!Number.isInteger(extraMinutes)||extraWork<0||extraWork>1000||extraMinutes<0||extraMinutes>100||extraWork+extraMinutes===0} onClick={()=>{const request={runId:run.id,requestId:id(),work:extraWork,minutes:extraMinutes,expected:budget!,confirmed:true as const};setConfirm({text:`追加普通投递${extraWork}次、秘书${extraMinutes}次？只增加本次流程额度，不开始任何环节，也不代表Token预算。`,action:async()=>{setBudgetRequest(request);writeLocal(`workflow-budget-request.${meetingId}`,request);await call('workflow-budget',request);setBudgetRequest(undefined);writeLocal(`workflow-budget-request.${meetingId}`,undefined);setPreview(undefined)}})}}>确认追加额度…</button>{budgetRequest&&<button style={button} disabled={busy} onClick={()=>{void action(async()=>{await call('workflow-budget',budgetRequest);setBudgetRequest(undefined);writeLocal(`workflow-budget-request.${meetingId}`,undefined);setPreview(undefined)})}}>重试同一次额度追加</button>}{budgetRequest&&<button style={button} disabled={busy} onClick={()=>setConfirm({text:'请先核对当前累计额度。清除本地请求不会撤销可能已生效的额度，也不会再次追加。',action:async()=>{setBudgetRequest(undefined);writeLocal(`workflow-budget-request.${meetingId}`,undefined)}})}>核对后清除待确认请求…</button>}</div></details>}
    <details><summary>轮次与操作记录（{run.events.length}）</summary>{[...run.events].reverse().map(e=><p key={e.id}>{new Date(e.time).toLocaleString()} · {e.action==='stage-materials'?(()=>{try{return JSON.parse(e.details).summary}catch{return '环节资料已暂存'}})():e.details}</p>)}{run.activations.map(a=><details key={a.id}><summary>{a.node.title} · 第{a.round||1}轮／尝试{a.attempt}{a.skipped?' · 已跳过':''}</summary><p>定义v{a.definitionRevision} · {a.id}</p><p>输入消息 {a.messageIds.join('、')||'无'}；来源执行 {a.sourceActivationIds.join('、')||'无'}</p></details>)}</details>
   </div></details>:undefined}
  />
  {!readOnly&&confirm&&<section role="alertdialog" aria-label="确认流程操作" style={{border:'2px solid #a55d00',padding:12,borderRadius:10}}><p>{confirm.text}</p><div className="rt-workflow-tools"><button style={button} disabled={busy} onClick={()=>{void action(async()=>{await confirm.action();setConfirm(undefined)})}}>确认</button><button style={button} disabled={busy} onClick={()=>setConfirm(undefined)}>取消</button></div></section>}
  {!readOnly&&edgeDraft&&<section ref={edgeSettingsRef} role="region" aria-label="连线设置" style={{border:'2px solid #2470b5',borderRadius:10,padding:12,display:'flex',flexDirection:'column',gap:8}}><strong>{edgeDraft.existing?'编辑连线':'建立连线'}：{d.nodes.find(n=>n.id===edgeDraft.from)?.title} → {d.nodes.find(n=>n.id===edgeDraft.to)?.title}</strong>{edgeLocked&&<p>此连线已冻结或当前只读。</p>}<label>连接方式<select aria-label="选中连线类型" style={input} disabled={edgeLocked} value={edgeDraft.kind} onChange={e=>setEdgeDraft({...edgeDraft,kind:e.target.value as WorkflowEdge['kind']})}><option value="flow">接着进行（顺序／并行）</option><option value="choice">由我选择（人工分支）</option><option value="loop">修改后再评审（返回）</option></select></label>{edgeDraft.kind==='choice'&&<label>选择名称<input aria-label="选中连线名称" placeholder="例如：通过、需要修改" style={input} disabled={edgeLocked} value={edgeDraft.label??''} onChange={e=>setEdgeDraft({...edgeDraft,label:e.target.value})}/></label>}{edgeDraft.kind==='loop'&&<label>返工范围<select aria-label="选中连线回路" style={input} disabled={edgeLocked} value={edgeDraft.loopId??''} onChange={e=>setEdgeDraft({...edgeDraft,loopId:e.target.value})}><option value="">请先在下方配置返工范围</option>{d.loops.map(l=><option key={l.id} value={l.id}>{d.nodes.find(n=>n.id===l.gateId)?.title??l.id}</option>)}</select></label>}<div className="rt-workflow-tools"><button style={button} disabled={edgeLocked} onClick={()=>applyEdge(edgeDraft,edgeDraft.existing?edgeDraft.id:undefined)}>{edgeDraft.existing?'应用连线修改':'确认连线'}</button>{edgeDraft.existing&&<button style={button} disabled={edgeLocked} onClick={()=>setConfirm({text:'删除所选连线？只改变编辑草稿，不会停止原窗口。',action:async()=>deleteEdge(edgeDraft.id)})}>删除所选连线…</button>}<button style={button} onClick={()=>setEdgeDraft(undefined)}>关闭连线设置</button></div></section>}
  {!readOnly&&bypass&&run&&<section role="alertdialog" aria-label="确认跳过处理" style={{padding:12,border:'2px solid #a55d00',borderRadius:10}}><p>跳过「{d.nodes.find(n=>n.id===bypass.nodeId)?.title}」的处理，后续仅沿用它已有的输入，并明确标注本环节已跳过。不会取消普通成员原窗口，下一环节仍需手动开始。</p><textarea aria-label="跳过原因" style={input} rows={2} value={bypass.reason} onChange={e=>setBypass({...bypass,reason:e.target.value})}/><div className="rt-workflow-tools"><button style={button} disabled={busy||!bypass.reason.trim()} onClick={()=>{void action(async()=>{await call('workflow-bypass',{runId:run.id,nodeId:bypass.nodeId,activationId:bypass.activationId,reason:bypass.reason,confirmed:true});setBypass(undefined)})}}>确认跳过并沿用输入</button><button style={button} disabled={busy} onClick={()=>setBypass(undefined)}>取消</button></div></section>}
  {!readOnly&&revisionTask&&<RevisionPanel key={revisionTask.taskId} meetingId={meetingId} task={revisionTask} memberName={name(revisionTask.toSessionId)} onChanged={onChanged} onClose={()=>setRevisionTarget(undefined)}/>}
  {!readOnly&&preview&&<section ref={previewRef} role="region" aria-label="流程执行预览" style={{padding:12,border:'2px solid #2470b5',borderRadius:12}}><b>确认本次输入与执行</b>
   {Object.entries(preview.plan.memberAvailability??{}).map(([id,status])=>!status.connected?<p key={id} role="status">{name(id)}：原窗口尚未加载。确认执行后插件核对并恢复同一原会话；归档、删除或状态无法确认时停止投递，可在成员边栏处理，不会创建替代会话。</p>:status.busy?<p key={id} role="status">{name(id)}：原窗口忙碌，本任务将等待，不能打断当前工作。</p>:null)}
   {preview.initial&&preview.collaboration==='automatic'&&<details open><summary>{preview.perNode?'本次逐环节运行的完整配置':'本次自动协作的完整配置'}</summary><p>{automaticSummary}</p><p>仅正式结构化结果推进；普通讨论和未批准任务卡不会推进。你随时可暂停或停止。</p></details>}
   <strong>确认本次输入与执行</strong>{preview.plan.items.map(item=><div key={item.node.id}><p><b>{item.node.title}</b> → {item.node.kind==='minutes'?'会议秘书':item.node.memberIds.map(name).join('、')} · 第{item.view.round||1}轮 · 约{item.characters}字符</p><p style={{whiteSpace:'pre-wrap'}}>{item.node.instruction}</p>{item.messageIds.map(messageId=><details key={messageId}><summary>引用：{messages.find(m=>m.id===messageId)?.text.slice(0,70)??messageId}</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{messages.find(m=>m.id===messageId)?.text}</p></details>)}{item.assetIds.map(assetId=><p key={assetId}>附件：{assets.find(a=>a.id===assetId)?.name} · v{assets.find(a=>a.id===assetId)?.version}</p>)}</div>)}
   {preview.plan.warnings?.map(w=><p role="alert" key={w}>{w}</p>)}{!preview.plan.ready&&<ul>{preview.plan.missing.map(x=><li key={x}>{x}</li>)}</ul>}<p>{preview.perNode?'只有已勾选环节可自动接收并运行，未勾选环节手动开始；保存不执行，验收、选路、异常与额度上限仍停下；重启需你确认继续。':preview.initial&&preview.collaboration==='automatic'?`确认后按整个保存模式自动接力：普通投递最多${d.limits.workAttempts}次，秘书最多${d.limits.minutesStarts}次；验收、选路和标为需确认的环节暂停，返工按设定上限停止；重启需你确认继续。`:'确认后仅开始上述环节。取消不会投递。'}</p><div className="rt-workflow-tools"><button style={button} disabled={busy||dirty||!preview.plan.ready||!!(preview.initial&&preview.collaboration==='automatic'&&(freeSteps&&preview.perNode&&preview.plan.automaticWarnings!==undefined?preview.plan.automaticWarnings.length:(!preview.perNode||(freeSteps?preview.plan.items.some(item=>item.node.autoReceiveAndRun===true):d.nodes.find(n=>n.id===d.entryId)?.autoReceiveAndRun===true))&&preview.plan.warnings?.length))} onClick={()=>{void start()}}>确认开始{preview.plan.items.length>1?` ${preview.plan.items.length} 个环节`:''}</button><button style={button} disabled={busy} onClick={()=>setPreview(undefined)}>取消预览</button></div>
  </section>}
  {!readOnly&&issues.length>0&&<div role="alert"><b>流程还有 {issues.length} 个问题</b><ul>{issues.map((e,i)=><li key={i}><button style={{...button,textAlign:'left'}} onClick={()=>{if(e.nodeId)setSelected(e.nodeId);else if(e.edgeId){const edge=d.edges.find(x=>x.id===e.edgeId);if(edge)setSelected(edge.from)}}}>{e.message}</button></li>)}</ul></div>}
  {!readOnly&&run&&ready.length>0&&<section ref={readySectionRef}><b>下一步可开始</b><div className="rt-workflow-tools" style={{marginTop:6}}>{ready.map(v=><button key={v.nodeId} style={button} disabled={busy||dirty||admissionBlocked||meeting.releasePaused} onClick={()=>{setSelected(v.nodeId);void inspect([v.nodeId])}}>预览：{d.nodes.find(n=>n.id===v.nodeId)?.title}</button>)}{d.parallelGroups.filter(g=>g.branchIds.every(nodeId=>ready.some(v=>v.nodeId===nodeId))).map(g=><button key={g.id} style={button} disabled={busy||dirty||admissionBlocked||meeting.releasePaused} onClick={()=>{void inspect(g.branchIds)}}>一起开始 {g.branchIds.length} 个并行环节…</button>)}</div></section>}
  {missingHistory||workflow&&!workflowSchemaSupported(workflow.schemaVersion)?<section aria-label="流程内容不可用" role="status">{missingHistory?'所选历史运行已不存在，当前配置不会冒充历史记录。请返回当前配置后查看。':'此流程版本当前无法解释，请升级到兼容版本后查看。'}</section>:<div className={sequenceMode?"rt-workflow-layout rt-workflow-list-layout":"rt-workflow-layout"} ref={contentRef}><div style={{minWidth:0,display:'flex',flexDirection:'column',gap:10}}>
   {!sequenceMode&&<div className="rt-workflow-content-heading"><h4 style={{margin:0,fontSize:14}}>会议环节</h4>{!readOnly&&!freeSteps&&<button style={button} onClick={()=>{if(!canMutate())return;let number=d.nodes.length+1;while(d.nodes.some(n=>n.title===('环节 '+number)))number++;const nodeId=id(),next:WorkflowNode={id:nodeId,title:`环节 ${number}`,kind:'work',memberIds:[],instruction:'',inputs:[],includeIncoming:true};edit({...d,entryId:d.entryId||nodeId,nodes:[...d.nodes,next],positions:{...d.positions,[nodeId]:{x:30+d.nodes.length%3*270,y:30+Math.floor(d.nodes.length/3)*180}}});setSelected(nodeId)}}>＋ 添加环节</button>}</div>}
   {mode==='graph'?<><div className="rt-workflow-tools">{!readOnly&&!freeSteps&&<button style={button} disabled={!d.nodes.length} onClick={()=>{const errors=validateWorkflowGraph(d);setIssues(errors);if(!errors.length)edit(layoutWorkflow(d),true)}}>整理图形</button>}<button style={button} onClick={()=>{setManualZoomRequest(n=>n+1);setZoom(z=>clampWorkflowZoom(z-.15))}}>缩小</button><span aria-live="polite" style={{alignSelf:'center'}}>{Math.round(zoom*100)}%</span><button style={button} onClick={()=>{setManualZoomRequest(n=>n+1);setZoom(z=>clampWorkflowZoom(z+.15))}}>放大</button><button style={button} onClick={()=>setFitRequest(n=>n+1)}>适配画布</button><small style={{alignSelf:'center'}}>Ctrl＋滚轮缩放</small></div><WorkflowCanvas definition={freeSteps?layoutWorkflow(d):d} views={views} run={run} selected={selected} onSelect={setSelected} zoom={zoom} onZoomChange={setZoom} fitRequest={fitRequest} manualZoomRequest={manualZoomRequest} members={members} readOnly={readOnly||freeSteps} selectedEdge={edgeDraft?.existing?edgeDraft.id:undefined} onSelectEdge={freeSteps?undefined:selectEdge} onConnect={freeSteps?undefined:connect} onMove={(nodeId,x,y)=>{if(!readOnly&&!freeSteps)edit({...d,positions:{...d.positions,[nodeId]:{x,y}}},true)}}/><small>{freeSteps?'此图仅查看步骤的依赖关系，请在步骤列表编辑。':<>拖动右侧圆点到下一环节左侧圆点连线；也可依次点击两点。点击连线可改类型或删除。拖节点调整位置，Alt＋方向键也可移动；编辑不执行任务。</>}</small></>:<WorkflowSteps definition={d} members={members} run={run} views={views} selected={selected} busy={busy} readOnly={readOnly} messages={messages} assets={assets} onSelect={setSelected} onEdit={editSteps} onPrepareEmpty={prepareEmpty} onShowGraph={()=>setMode('graph')} onOpenMembers={()=>onNavigate?.('members')} renderExecution={nodeId=>nodeId===node?.id?execution:undefined}/>}
   {!sequenceMode&&execution}
  </div>{!sequenceMode&&!freeSteps&&node&&<WorkflowInspector key={`${meetingId}:${d.id}:${node.id}:${historyId}`} definition={d} node={node} view={mode} members={members} messages={messages} assets={assets} run={active} readOnly={readOnly||freeSteps} onChange={next=>{if(!validInspector()||freeSteps||next.id!==node.id)return;previewEpoch.current.version++;setConfirmRaw(undefined);setDraft(current=>current.definition.id===d.id&&current.definition.nodes.some(n=>n.id===next.id)?{...current,definition:{...current.definition,nodes:current.definition.nodes.map(n=>n.id===next.id?next:n)}}:current);setDirty(true);setIssues([]);setPreview(undefined)}} onRemove={()=>{if(!validInspector()||freeSteps)return;setConfirm({text:`删除“${node.title}”及相连路线？相关并行组和回路配置需要重新检查。`,action:async()=>{if(!validInspector())throw new Error('当前环节已切换，请重新选择后删除');edit(removeWorkflowNode(d,node.id,active));setSelected('');setEdgeDraft(undefined)}})}}/>}</div>}
  {!readOnly&&!sequenceMode&&!freeSteps&&<details><summary title="顺序是接着处理；并行是多人同时处理后汇合；返工是你选择修改后重新评审。">更多流程设置：连线、同时处理与返工</summary>{!frozen&&<details><summary>高级起点：分支与返工</summary><button style={button} disabled={busy} onClick={()=>setConfirm({text:'将编辑区替换为三人评审示例。你可以调整成员和要求；载入不会执行。',action:async()=>{edit(template(members));setSelected('proposal');setMode('graph')}})}>载入分支返工示例</button></details>}<div className="rt-workflow-field" style={{marginTop:10}}><label>流程名称<input aria-label="流程名称" style={input} value={d.title} onChange={e=>edit({...d,title:e.target.value})}/></label><label>起始环节{nodeOptions(d.entryId,v=>edit({...d,entryId:v}),'起始环节')}</label>
   <fieldset style={{minWidth:0}}><legend>添加连线</legend><div className="rt-workflow-field">{nodeOptions(from,setFrom,'连线起点')}{nodeOptions(to,setTo,'连线终点')}<select aria-label="连线类型" style={input} value={edgeKind} onChange={e=>setEdgeKind(e.target.value as typeof edgeKind)}><option value="flow">顺序／并行分支</option><option value="choice">人工选择出口</option><option value="loop">返回下一轮</option></select>{edgeKind==='choice'&&<input aria-label="出口名称" placeholder="例如：通过、需要修改" style={input} value={edgeLabel} onChange={e=>setEdgeLabel(e.target.value)}/>} {edgeKind==='loop'&&<select aria-label="所属回路" style={input} value={edgeLoop} onChange={e=>setEdgeLoop(e.target.value)}><option value="">选择回路</option>{d.loops.map(l=><option key={l.id} value={l.id}>{d.nodes.find(n=>n.id===l.gateId)?.title??l.id}</option>)}</select>}<button style={button} disabled={!from||!to||from===to} onClick={()=>applyEdge({id:id(),from,to,kind:edgeKind,...(edgeKind==='choice'?{label:edgeLabel}:{}),...(edgeKind==='loop'?{loopId:edgeLoop}:{})})}>连接这两个环节</button></div></fieldset>
   {d.edges.map(e=><div key={e.id} style={{display:'flex',alignItems:'center',gap:6,flexWrap:'wrap'}}><span>{d.nodes.find(n=>n.id===e.from)?.title} → {d.nodes.find(n=>n.id===e.to)?.title} · {e.label??(e.kind==='loop'?'返回下一轮':'顺序')}</span><button style={button} aria-label={`删除连线 ${e.id}`} onClick={()=>deleteEdge(e.id)}>移除</button></div>)}
   <button style={button} disabled={frozen} onClick={()=>edit({...d,parallelGroups:[...d.parallelGroups,{id:id(),sourceId:'',branchIds:[],joinId:''}]})}>＋ 添加并行组</button>{d.parallelGroups.map((g,i)=><fieldset key={g.id} disabled={frozen} style={{minWidth:0}}><legend title="从同一环节分给多人，等所需结果都返回再继续。">同时处理组 {i+1}</legend><label>分支来源{nodeOptions(g.sourceId,v=>edit({...d,parallelGroups:d.parallelGroups.map(x=>x.id===g.id?{...x,sourceId:v}:x)}),'并行来源')}</label><label>汇合到{nodeOptions(g.joinId,v=>edit({...d,parallelGroups:d.parallelGroups.map(x=>x.id===g.id?{...x,joinId:v}:x)}),'并行汇合')}</label><p>选中此组实际并行的入口，并连接来源和汇合节点。</p>{d.nodes.map(n=><label key={n.id} style={{display:'block'}}><input type="checkbox" checked={g.branchIds.includes(n.id)} onChange={()=>edit({...d,parallelGroups:d.parallelGroups.map(x=>x.id===g.id?{...x,branchIds:x.branchIds.includes(n.id)?x.branchIds.filter(k=>k!==n.id):[...x.branchIds,n.id]}:x)})}/>{n.title}</label>)}<button style={button} onClick={()=>edit({...d,parallelGroups:d.parallelGroups.filter(x=>x.id!==g.id)})}>移除并行组配置</button></fieldset>)}
   <button style={button} disabled={frozen} onClick={()=>edit({...d,loops:[...d.loops,{id:id(),nodeIds:[],entryIds:[],gateId:'',advanceId:'',maxRounds:3}]})}>＋ 添加受控回路</button><p>第一版支持独立回路，不支持嵌套／交叉回路。每个回路必须有人工出口和返回连线。</p>{d.loops.map((l,i)=><fieldset key={l.id} disabled={frozen} style={{minWidth:0}}><legend title="评审后由你选择通过或修改；修改完成后回到指定评审入口。">返工范围 {i+1}</legend><label>决定通过或修改{nodeOptions(l.gateId,v=>edit({...d,loops:d.loops.map(x=>x.id===l.id?{...x,gateId:v}:x)}),'回路决策门')}</label><label>修改环节{nodeOptions(l.advanceId,v=>edit({...d,loops:d.loops.map(x=>x.id===l.id?{...x,advanceId:v}:x)}),'回路修改环节')}</label><p>手动返工每轮由你预览并开始，不限制轮数；自动接力到达下列上限时暂停，须明确追加才能继续。</p><label>自动轮次上限<input aria-label={`自动轮次上限 ${i+1}`} type="number" min={1} style={input} value={l.maxRounds} onChange={e=>edit({...d,loops:d.loops.map(x=>x.id===l.id?{...x,maxRounds:Number(e.target.value)}:x)})}/></label><p>回路范围包含评审、汇合和修改；返回入口是修改后重新评审的位置。</p>{d.nodes.map(n=><div key={n.id}><label><input type="checkbox" checked={l.nodeIds.includes(n.id)} onChange={()=>edit({...d,loops:d.loops.map(x=>x.id===l.id?{...x,nodeIds:x.nodeIds.includes(n.id)?x.nodeIds.filter(k=>k!==n.id):[...x.nodeIds,n.id]}:x)})}/>{n.title}</label> <label><input type="checkbox" checked={l.entryIds.includes(n.id)} onChange={()=>edit({...d,loops:d.loops.map(x=>x.id===l.id?{...x,entryIds:x.entryIds.includes(n.id)?x.entryIds.filter(k=>k!==n.id):[...x.entryIds,n.id]}:x)})}/>返回入口</label></div>)}<button style={button} onClick={()=>edit({...d,loops:d.loops.filter(x=>x.id!==l.id),edges:d.edges.filter(e=>e.loopId!==l.id)})}>移除此回路和返回边</button></fieldset>)}
   <fieldset disabled={!!active} style={{minWidth:0}}><legend>本次运行额度</legend>{([['nodeAttempts','每节点每轮尝试'],['workAttempts','普通成员投递总数'],['minutesStarts','秘书生成发起数']] as const).map(([key,label])=><label key={key} style={{display:'block'}}>{label}<input aria-label={label} type="number" min={1} style={input} value={d.limits[key]} onChange={e=>edit({...d,limits:{...d.limits,[key]:Number(e.target.value)}})}/></label>)}</fieldset>
  </div></details>}
 </section>
}
